
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser.ts'
export { Prisma }
export * as $Enums from './enums.ts'
export * from './enums.ts';
/**
 * Model data_fiber
 * 
 */
export type data_fiber = Prisma.data_fiberModel
/**
 * Model log_komplain
 * 
 */
export type log_komplain = Prisma.log_komplainModel
/**
 * Model snmp
 * 
 */
export type snmp = Prisma.snmpModel
/**
 * Model snmp_devices
 * 
 */
export type snmp_devices = Prisma.snmp_devicesModel
/**
 * Model users
 * 
 */
export type users = Prisma.usersModel
