
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/data_fiber.ts'
export type * from './models/log_komplain.ts'
export type * from './models/snmp.ts'
export type * from './models/snmp_devices.ts'
export type * from './models/users.ts'
export type * from './commonInputTypes.ts'