
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models.ts'
export type * from './prismaNamespace.ts'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.objectEnumValues.classes.DbNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.DbNull),
  JsonNull: runtime.objectEnumValues.classes.JsonNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.JsonNull),
  AnyNull: runtime.objectEnumValues.classes.AnyNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.objectEnumValues.instances.DbNull
/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.objectEnumValues.instances.JsonNull
/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.objectEnumValues.instances.AnyNull


export const ModelName = {
  data_fiber: 'data_fiber',
  log_komplain: 'log_komplain',
  snmp: 'snmp',
  snmp_devices: 'snmp_devices',
  users: 'users'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const Data_fiberScalarFieldEnum = {
  user_pppoe: 'user_pppoe',
  name: 'name',
  alamat: 'alamat',
  olt_name: 'olt_name',
  olt_port: 'olt_port',
  onu_sn: 'onu_sn',
  pppoe_password: 'pppoe_password',
  interface: 'interface',
  onu_id: 'onu_id',
  sheet: 'sheet',
  paket: 'paket',
  updated_at: 'updated_at'
} as const

export type Data_fiberScalarFieldEnum = (typeof Data_fiberScalarFieldEnum)[keyof typeof Data_fiberScalarFieldEnum]


export const Log_komplainScalarFieldEnum = {
  id: 'id',
  tiket: 'tiket',
  tanggal: 'tanggal',
  waktu: 'waktu',
  nama: 'nama',
  kendala: 'kendala',
  status: 'status',
  action: 'action',
  note: 'note',
  pic: 'pic',
  last_updated: 'last_updated',
  onu_sn: 'onu_sn'
} as const

export type Log_komplainScalarFieldEnum = (typeof Log_komplainScalarFieldEnum)[keyof typeof Log_komplainScalarFieldEnum]


export const SnmpScalarFieldEnum = {
  olt_name: 'olt_name',
  interface: 'interface',
  name: 'name',
  address: 'address',
  sn: 'sn',
  modem_type: 'modem_type',
  status: 'status',
  last_uptime: 'last_uptime',
  rx_power_dbm: 'rx_power_dbm',
  rx_power_str: 'rx_power_str',
  raw_ifindex: 'raw_ifindex',
  raw_onuid: 'raw_onuid',
  last_updated: 'last_updated'
} as const

export type SnmpScalarFieldEnum = (typeof SnmpScalarFieldEnum)[keyof typeof SnmpScalarFieldEnum]


export const Snmp_devicesScalarFieldEnum = {
  name: 'name',
  host: 'host',
  community_string: 'community_string'
} as const

export type Snmp_devicesScalarFieldEnum = (typeof Snmp_devicesScalarFieldEnum)[keyof typeof Snmp_devicesScalarFieldEnum]


export const UsersScalarFieldEnum = {
  id: 'id',
  username: 'username',
  full_name: 'full_name',
  role: 'role',
  created_at: 'created_at',
  password: 'password',
  hashed_password: 'hashed_password'
} as const

export type UsersScalarFieldEnum = (typeof UsersScalarFieldEnum)[keyof typeof UsersScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

