
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `data_fiber` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model data_fiber
 * 
 */
export type data_fiberModel = runtime.Types.Result.DefaultSelection<Prisma.$data_fiberPayload>

export type AggregateData_fiber = {
  _count: Data_fiberCountAggregateOutputType | null
  _min: Data_fiberMinAggregateOutputType | null
  _max: Data_fiberMaxAggregateOutputType | null
}

export type Data_fiberMinAggregateOutputType = {
  user_pppoe: string | null
  name: string | null
  alamat: string | null
  olt_name: string | null
  olt_port: string | null
  onu_sn: string | null
  pppoe_password: string | null
  interface: string | null
  onu_id: string | null
  sheet: string | null
  paket: string | null
  updated_at: Date | null
}

export type Data_fiberMaxAggregateOutputType = {
  user_pppoe: string | null
  name: string | null
  alamat: string | null
  olt_name: string | null
  olt_port: string | null
  onu_sn: string | null
  pppoe_password: string | null
  interface: string | null
  onu_id: string | null
  sheet: string | null
  paket: string | null
  updated_at: Date | null
}

export type Data_fiberCountAggregateOutputType = {
  user_pppoe: number
  name: number
  alamat: number
  olt_name: number
  olt_port: number
  onu_sn: number
  pppoe_password: number
  interface: number
  onu_id: number
  sheet: number
  paket: number
  updated_at: number
  _all: number
}


export type Data_fiberMinAggregateInputType = {
  user_pppoe?: true
  name?: true
  alamat?: true
  olt_name?: true
  olt_port?: true
  onu_sn?: true
  pppoe_password?: true
  interface?: true
  onu_id?: true
  sheet?: true
  paket?: true
  updated_at?: true
}

export type Data_fiberMaxAggregateInputType = {
  user_pppoe?: true
  name?: true
  alamat?: true
  olt_name?: true
  olt_port?: true
  onu_sn?: true
  pppoe_password?: true
  interface?: true
  onu_id?: true
  sheet?: true
  paket?: true
  updated_at?: true
}

export type Data_fiberCountAggregateInputType = {
  user_pppoe?: true
  name?: true
  alamat?: true
  olt_name?: true
  olt_port?: true
  onu_sn?: true
  pppoe_password?: true
  interface?: true
  onu_id?: true
  sheet?: true
  paket?: true
  updated_at?: true
  _all?: true
}

export type Data_fiberAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which data_fiber to aggregate.
   */
  where?: Prisma.data_fiberWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of data_fibers to fetch.
   */
  orderBy?: Prisma.data_fiberOrderByWithRelationInput | Prisma.data_fiberOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.data_fiberWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` data_fibers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` data_fibers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned data_fibers
  **/
  _count?: true | Data_fiberCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Data_fiberMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Data_fiberMaxAggregateInputType
}

export type GetData_fiberAggregateType<T extends Data_fiberAggregateArgs> = {
      [P in keyof T & keyof AggregateData_fiber]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateData_fiber[P]>
    : Prisma.GetScalarType<T[P], AggregateData_fiber[P]>
}




export type data_fiberGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.data_fiberWhereInput
  orderBy?: Prisma.data_fiberOrderByWithAggregationInput | Prisma.data_fiberOrderByWithAggregationInput[]
  by: Prisma.Data_fiberScalarFieldEnum[] | Prisma.Data_fiberScalarFieldEnum
  having?: Prisma.data_fiberScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Data_fiberCountAggregateInputType | true
  _min?: Data_fiberMinAggregateInputType
  _max?: Data_fiberMaxAggregateInputType
}

export type Data_fiberGroupByOutputType = {
  user_pppoe: string
  name: string | null
  alamat: string | null
  olt_name: string | null
  olt_port: string | null
  onu_sn: string | null
  pppoe_password: string | null
  interface: string | null
  onu_id: string | null
  sheet: string | null
  paket: string | null
  updated_at: Date | null
  _count: Data_fiberCountAggregateOutputType | null
  _min: Data_fiberMinAggregateOutputType | null
  _max: Data_fiberMaxAggregateOutputType | null
}

type GetData_fiberGroupByPayload<T extends data_fiberGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Data_fiberGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Data_fiberGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Data_fiberGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Data_fiberGroupByOutputType[P]>
      }
    >
  >



export type data_fiberWhereInput = {
  AND?: Prisma.data_fiberWhereInput | Prisma.data_fiberWhereInput[]
  OR?: Prisma.data_fiberWhereInput[]
  NOT?: Prisma.data_fiberWhereInput | Prisma.data_fiberWhereInput[]
  user_pppoe?: Prisma.StringFilter<"data_fiber"> | string
  name?: Prisma.StringNullableFilter<"data_fiber"> | string | null
  alamat?: Prisma.StringNullableFilter<"data_fiber"> | string | null
  olt_name?: Prisma.StringNullableFilter<"data_fiber"> | string | null
  olt_port?: Prisma.StringNullableFilter<"data_fiber"> | string | null
  onu_sn?: Prisma.StringNullableFilter<"data_fiber"> | string | null
  pppoe_password?: Prisma.StringNullableFilter<"data_fiber"> | string | null
  interface?: Prisma.StringNullableFilter<"data_fiber"> | string | null
  onu_id?: Prisma.StringNullableFilter<"data_fiber"> | string | null
  sheet?: Prisma.StringNullableFilter<"data_fiber"> | string | null
  paket?: Prisma.StringNullableFilter<"data_fiber"> | string | null
  updated_at?: Prisma.DateTimeNullableFilter<"data_fiber"> | Date | string | null
}

export type data_fiberOrderByWithRelationInput = {
  user_pppoe?: Prisma.SortOrder
  name?: Prisma.SortOrderInput | Prisma.SortOrder
  alamat?: Prisma.SortOrderInput | Prisma.SortOrder
  olt_name?: Prisma.SortOrderInput | Prisma.SortOrder
  olt_port?: Prisma.SortOrderInput | Prisma.SortOrder
  onu_sn?: Prisma.SortOrderInput | Prisma.SortOrder
  pppoe_password?: Prisma.SortOrderInput | Prisma.SortOrder
  interface?: Prisma.SortOrderInput | Prisma.SortOrder
  onu_id?: Prisma.SortOrderInput | Prisma.SortOrder
  sheet?: Prisma.SortOrderInput | Prisma.SortOrder
  paket?: Prisma.SortOrderInput | Prisma.SortOrder
  updated_at?: Prisma.SortOrderInput | Prisma.SortOrder
}

export type data_fiberWhereUniqueInput = Prisma.AtLeast<{
  user_pppoe?: string
  AND?: Prisma.data_fiberWhereInput | Prisma.data_fiberWhereInput[]
  OR?: Prisma.data_fiberWhereInput[]
  NOT?: Prisma.data_fiberWhereInput | Prisma.data_fiberWhereInput[]
  name?: Prisma.StringNullableFilter<"data_fiber"> | string | null
  alamat?: Prisma.StringNullableFilter<"data_fiber"> | string | null
  olt_name?: Prisma.StringNullableFilter<"data_fiber"> | string | null
  olt_port?: Prisma.StringNullableFilter<"data_fiber"> | string | null
  onu_sn?: Prisma.StringNullableFilter<"data_fiber"> | string | null
  pppoe_password?: Prisma.StringNullableFilter<"data_fiber"> | string | null
  interface?: Prisma.StringNullableFilter<"data_fiber"> | string | null
  onu_id?: Prisma.StringNullableFilter<"data_fiber"> | string | null
  sheet?: Prisma.StringNullableFilter<"data_fiber"> | string | null
  paket?: Prisma.StringNullableFilter<"data_fiber"> | string | null
  updated_at?: Prisma.DateTimeNullableFilter<"data_fiber"> | Date | string | null
}, "user_pppoe">

export type data_fiberOrderByWithAggregationInput = {
  user_pppoe?: Prisma.SortOrder
  name?: Prisma.SortOrderInput | Prisma.SortOrder
  alamat?: Prisma.SortOrderInput | Prisma.SortOrder
  olt_name?: Prisma.SortOrderInput | Prisma.SortOrder
  olt_port?: Prisma.SortOrderInput | Prisma.SortOrder
  onu_sn?: Prisma.SortOrderInput | Prisma.SortOrder
  pppoe_password?: Prisma.SortOrderInput | Prisma.SortOrder
  interface?: Prisma.SortOrderInput | Prisma.SortOrder
  onu_id?: Prisma.SortOrderInput | Prisma.SortOrder
  sheet?: Prisma.SortOrderInput | Prisma.SortOrder
  paket?: Prisma.SortOrderInput | Prisma.SortOrder
  updated_at?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.data_fiberCountOrderByAggregateInput
  _max?: Prisma.data_fiberMaxOrderByAggregateInput
  _min?: Prisma.data_fiberMinOrderByAggregateInput
}

export type data_fiberScalarWhereWithAggregatesInput = {
  AND?: Prisma.data_fiberScalarWhereWithAggregatesInput | Prisma.data_fiberScalarWhereWithAggregatesInput[]
  OR?: Prisma.data_fiberScalarWhereWithAggregatesInput[]
  NOT?: Prisma.data_fiberScalarWhereWithAggregatesInput | Prisma.data_fiberScalarWhereWithAggregatesInput[]
  user_pppoe?: Prisma.StringWithAggregatesFilter<"data_fiber"> | string
  name?: Prisma.StringNullableWithAggregatesFilter<"data_fiber"> | string | null
  alamat?: Prisma.StringNullableWithAggregatesFilter<"data_fiber"> | string | null
  olt_name?: Prisma.StringNullableWithAggregatesFilter<"data_fiber"> | string | null
  olt_port?: Prisma.StringNullableWithAggregatesFilter<"data_fiber"> | string | null
  onu_sn?: Prisma.StringNullableWithAggregatesFilter<"data_fiber"> | string | null
  pppoe_password?: Prisma.StringNullableWithAggregatesFilter<"data_fiber"> | string | null
  interface?: Prisma.StringNullableWithAggregatesFilter<"data_fiber"> | string | null
  onu_id?: Prisma.StringNullableWithAggregatesFilter<"data_fiber"> | string | null
  sheet?: Prisma.StringNullableWithAggregatesFilter<"data_fiber"> | string | null
  paket?: Prisma.StringNullableWithAggregatesFilter<"data_fiber"> | string | null
  updated_at?: Prisma.DateTimeNullableWithAggregatesFilter<"data_fiber"> | Date | string | null
}

export type data_fiberCreateInput = {
  user_pppoe: string
  name?: string | null
  alamat?: string | null
  olt_name?: string | null
  olt_port?: string | null
  onu_sn?: string | null
  pppoe_password?: string | null
  interface?: string | null
  onu_id?: string | null
  sheet?: string | null
  paket?: string | null
  updated_at?: Date | string | null
}

export type data_fiberUncheckedCreateInput = {
  user_pppoe: string
  name?: string | null
  alamat?: string | null
  olt_name?: string | null
  olt_port?: string | null
  onu_sn?: string | null
  pppoe_password?: string | null
  interface?: string | null
  onu_id?: string | null
  sheet?: string | null
  paket?: string | null
  updated_at?: Date | string | null
}

export type data_fiberUpdateInput = {
  user_pppoe?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  alamat?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  olt_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  olt_port?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  onu_sn?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pppoe_password?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  interface?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  onu_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sheet?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  paket?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type data_fiberUncheckedUpdateInput = {
  user_pppoe?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  alamat?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  olt_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  olt_port?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  onu_sn?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pppoe_password?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  interface?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  onu_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sheet?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  paket?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type data_fiberCreateManyInput = {
  user_pppoe: string
  name?: string | null
  alamat?: string | null
  olt_name?: string | null
  olt_port?: string | null
  onu_sn?: string | null
  pppoe_password?: string | null
  interface?: string | null
  onu_id?: string | null
  sheet?: string | null
  paket?: string | null
  updated_at?: Date | string | null
}

export type data_fiberUpdateManyMutationInput = {
  user_pppoe?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  alamat?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  olt_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  olt_port?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  onu_sn?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pppoe_password?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  interface?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  onu_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sheet?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  paket?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type data_fiberUncheckedUpdateManyInput = {
  user_pppoe?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  alamat?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  olt_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  olt_port?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  onu_sn?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pppoe_password?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  interface?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  onu_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sheet?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  paket?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type data_fiberCountOrderByAggregateInput = {
  user_pppoe?: Prisma.SortOrder
  name?: Prisma.SortOrder
  alamat?: Prisma.SortOrder
  olt_name?: Prisma.SortOrder
  olt_port?: Prisma.SortOrder
  onu_sn?: Prisma.SortOrder
  pppoe_password?: Prisma.SortOrder
  interface?: Prisma.SortOrder
  onu_id?: Prisma.SortOrder
  sheet?: Prisma.SortOrder
  paket?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type data_fiberMaxOrderByAggregateInput = {
  user_pppoe?: Prisma.SortOrder
  name?: Prisma.SortOrder
  alamat?: Prisma.SortOrder
  olt_name?: Prisma.SortOrder
  olt_port?: Prisma.SortOrder
  onu_sn?: Prisma.SortOrder
  pppoe_password?: Prisma.SortOrder
  interface?: Prisma.SortOrder
  onu_id?: Prisma.SortOrder
  sheet?: Prisma.SortOrder
  paket?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type data_fiberMinOrderByAggregateInput = {
  user_pppoe?: Prisma.SortOrder
  name?: Prisma.SortOrder
  alamat?: Prisma.SortOrder
  olt_name?: Prisma.SortOrder
  olt_port?: Prisma.SortOrder
  onu_sn?: Prisma.SortOrder
  pppoe_password?: Prisma.SortOrder
  interface?: Prisma.SortOrder
  onu_id?: Prisma.SortOrder
  sheet?: Prisma.SortOrder
  paket?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}



export type data_fiberSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  user_pppoe?: boolean
  name?: boolean
  alamat?: boolean
  olt_name?: boolean
  olt_port?: boolean
  onu_sn?: boolean
  pppoe_password?: boolean
  interface?: boolean
  onu_id?: boolean
  sheet?: boolean
  paket?: boolean
  updated_at?: boolean
}, ExtArgs["result"]["data_fiber"]>

export type data_fiberSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  user_pppoe?: boolean
  name?: boolean
  alamat?: boolean
  olt_name?: boolean
  olt_port?: boolean
  onu_sn?: boolean
  pppoe_password?: boolean
  interface?: boolean
  onu_id?: boolean
  sheet?: boolean
  paket?: boolean
  updated_at?: boolean
}, ExtArgs["result"]["data_fiber"]>

export type data_fiberSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  user_pppoe?: boolean
  name?: boolean
  alamat?: boolean
  olt_name?: boolean
  olt_port?: boolean
  onu_sn?: boolean
  pppoe_password?: boolean
  interface?: boolean
  onu_id?: boolean
  sheet?: boolean
  paket?: boolean
  updated_at?: boolean
}, ExtArgs["result"]["data_fiber"]>

export type data_fiberSelectScalar = {
  user_pppoe?: boolean
  name?: boolean
  alamat?: boolean
  olt_name?: boolean
  olt_port?: boolean
  onu_sn?: boolean
  pppoe_password?: boolean
  interface?: boolean
  onu_id?: boolean
  sheet?: boolean
  paket?: boolean
  updated_at?: boolean
}

export type data_fiberOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"user_pppoe" | "name" | "alamat" | "olt_name" | "olt_port" | "onu_sn" | "pppoe_password" | "interface" | "onu_id" | "sheet" | "paket" | "updated_at", ExtArgs["result"]["data_fiber"]>

export type $data_fiberPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "data_fiber"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    user_pppoe: string
    name: string | null
    alamat: string | null
    olt_name: string | null
    olt_port: string | null
    onu_sn: string | null
    pppoe_password: string | null
    interface: string | null
    onu_id: string | null
    sheet: string | null
    paket: string | null
    updated_at: Date | null
  }, ExtArgs["result"]["data_fiber"]>
  composites: {}
}

export type data_fiberGetPayload<S extends boolean | null | undefined | data_fiberDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$data_fiberPayload, S>

export type data_fiberCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<data_fiberFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Data_fiberCountAggregateInputType | true
  }

export interface data_fiberDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['data_fiber'], meta: { name: 'data_fiber' } }
  /**
   * Find zero or one Data_fiber that matches the filter.
   * @param {data_fiberFindUniqueArgs} args - Arguments to find a Data_fiber
   * @example
   * // Get one Data_fiber
   * const data_fiber = await prisma.data_fiber.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends data_fiberFindUniqueArgs>(args: Prisma.SelectSubset<T, data_fiberFindUniqueArgs<ExtArgs>>): Prisma.Prisma__data_fiberClient<runtime.Types.Result.GetResult<Prisma.$data_fiberPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Data_fiber that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {data_fiberFindUniqueOrThrowArgs} args - Arguments to find a Data_fiber
   * @example
   * // Get one Data_fiber
   * const data_fiber = await prisma.data_fiber.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends data_fiberFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, data_fiberFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__data_fiberClient<runtime.Types.Result.GetResult<Prisma.$data_fiberPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Data_fiber that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {data_fiberFindFirstArgs} args - Arguments to find a Data_fiber
   * @example
   * // Get one Data_fiber
   * const data_fiber = await prisma.data_fiber.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends data_fiberFindFirstArgs>(args?: Prisma.SelectSubset<T, data_fiberFindFirstArgs<ExtArgs>>): Prisma.Prisma__data_fiberClient<runtime.Types.Result.GetResult<Prisma.$data_fiberPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Data_fiber that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {data_fiberFindFirstOrThrowArgs} args - Arguments to find a Data_fiber
   * @example
   * // Get one Data_fiber
   * const data_fiber = await prisma.data_fiber.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends data_fiberFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, data_fiberFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__data_fiberClient<runtime.Types.Result.GetResult<Prisma.$data_fiberPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Data_fibers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {data_fiberFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Data_fibers
   * const data_fibers = await prisma.data_fiber.findMany()
   * 
   * // Get first 10 Data_fibers
   * const data_fibers = await prisma.data_fiber.findMany({ take: 10 })
   * 
   * // Only select the `user_pppoe`
   * const data_fiberWithUser_pppoeOnly = await prisma.data_fiber.findMany({ select: { user_pppoe: true } })
   * 
   */
  findMany<T extends data_fiberFindManyArgs>(args?: Prisma.SelectSubset<T, data_fiberFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$data_fiberPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Data_fiber.
   * @param {data_fiberCreateArgs} args - Arguments to create a Data_fiber.
   * @example
   * // Create one Data_fiber
   * const Data_fiber = await prisma.data_fiber.create({
   *   data: {
   *     // ... data to create a Data_fiber
   *   }
   * })
   * 
   */
  create<T extends data_fiberCreateArgs>(args: Prisma.SelectSubset<T, data_fiberCreateArgs<ExtArgs>>): Prisma.Prisma__data_fiberClient<runtime.Types.Result.GetResult<Prisma.$data_fiberPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Data_fibers.
   * @param {data_fiberCreateManyArgs} args - Arguments to create many Data_fibers.
   * @example
   * // Create many Data_fibers
   * const data_fiber = await prisma.data_fiber.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends data_fiberCreateManyArgs>(args?: Prisma.SelectSubset<T, data_fiberCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Data_fibers and returns the data saved in the database.
   * @param {data_fiberCreateManyAndReturnArgs} args - Arguments to create many Data_fibers.
   * @example
   * // Create many Data_fibers
   * const data_fiber = await prisma.data_fiber.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Data_fibers and only return the `user_pppoe`
   * const data_fiberWithUser_pppoeOnly = await prisma.data_fiber.createManyAndReturn({
   *   select: { user_pppoe: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends data_fiberCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, data_fiberCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$data_fiberPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Data_fiber.
   * @param {data_fiberDeleteArgs} args - Arguments to delete one Data_fiber.
   * @example
   * // Delete one Data_fiber
   * const Data_fiber = await prisma.data_fiber.delete({
   *   where: {
   *     // ... filter to delete one Data_fiber
   *   }
   * })
   * 
   */
  delete<T extends data_fiberDeleteArgs>(args: Prisma.SelectSubset<T, data_fiberDeleteArgs<ExtArgs>>): Prisma.Prisma__data_fiberClient<runtime.Types.Result.GetResult<Prisma.$data_fiberPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Data_fiber.
   * @param {data_fiberUpdateArgs} args - Arguments to update one Data_fiber.
   * @example
   * // Update one Data_fiber
   * const data_fiber = await prisma.data_fiber.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends data_fiberUpdateArgs>(args: Prisma.SelectSubset<T, data_fiberUpdateArgs<ExtArgs>>): Prisma.Prisma__data_fiberClient<runtime.Types.Result.GetResult<Prisma.$data_fiberPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Data_fibers.
   * @param {data_fiberDeleteManyArgs} args - Arguments to filter Data_fibers to delete.
   * @example
   * // Delete a few Data_fibers
   * const { count } = await prisma.data_fiber.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends data_fiberDeleteManyArgs>(args?: Prisma.SelectSubset<T, data_fiberDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Data_fibers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {data_fiberUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Data_fibers
   * const data_fiber = await prisma.data_fiber.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends data_fiberUpdateManyArgs>(args: Prisma.SelectSubset<T, data_fiberUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Data_fibers and returns the data updated in the database.
   * @param {data_fiberUpdateManyAndReturnArgs} args - Arguments to update many Data_fibers.
   * @example
   * // Update many Data_fibers
   * const data_fiber = await prisma.data_fiber.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Data_fibers and only return the `user_pppoe`
   * const data_fiberWithUser_pppoeOnly = await prisma.data_fiber.updateManyAndReturn({
   *   select: { user_pppoe: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends data_fiberUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, data_fiberUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$data_fiberPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Data_fiber.
   * @param {data_fiberUpsertArgs} args - Arguments to update or create a Data_fiber.
   * @example
   * // Update or create a Data_fiber
   * const data_fiber = await prisma.data_fiber.upsert({
   *   create: {
   *     // ... data to create a Data_fiber
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Data_fiber we want to update
   *   }
   * })
   */
  upsert<T extends data_fiberUpsertArgs>(args: Prisma.SelectSubset<T, data_fiberUpsertArgs<ExtArgs>>): Prisma.Prisma__data_fiberClient<runtime.Types.Result.GetResult<Prisma.$data_fiberPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Data_fibers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {data_fiberCountArgs} args - Arguments to filter Data_fibers to count.
   * @example
   * // Count the number of Data_fibers
   * const count = await prisma.data_fiber.count({
   *   where: {
   *     // ... the filter for the Data_fibers we want to count
   *   }
   * })
  **/
  count<T extends data_fiberCountArgs>(
    args?: Prisma.Subset<T, data_fiberCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Data_fiberCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Data_fiber.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Data_fiberAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Data_fiberAggregateArgs>(args: Prisma.Subset<T, Data_fiberAggregateArgs>): Prisma.PrismaPromise<GetData_fiberAggregateType<T>>

  /**
   * Group by Data_fiber.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {data_fiberGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends data_fiberGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: data_fiberGroupByArgs['orderBy'] }
      : { orderBy?: data_fiberGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, data_fiberGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetData_fiberGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the data_fiber model
 */
readonly fields: data_fiberFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for data_fiber.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__data_fiberClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the data_fiber model
 */
export interface data_fiberFieldRefs {
  readonly user_pppoe: Prisma.FieldRef<"data_fiber", 'String'>
  readonly name: Prisma.FieldRef<"data_fiber", 'String'>
  readonly alamat: Prisma.FieldRef<"data_fiber", 'String'>
  readonly olt_name: Prisma.FieldRef<"data_fiber", 'String'>
  readonly olt_port: Prisma.FieldRef<"data_fiber", 'String'>
  readonly onu_sn: Prisma.FieldRef<"data_fiber", 'String'>
  readonly pppoe_password: Prisma.FieldRef<"data_fiber", 'String'>
  readonly interface: Prisma.FieldRef<"data_fiber", 'String'>
  readonly onu_id: Prisma.FieldRef<"data_fiber", 'String'>
  readonly sheet: Prisma.FieldRef<"data_fiber", 'String'>
  readonly paket: Prisma.FieldRef<"data_fiber", 'String'>
  readonly updated_at: Prisma.FieldRef<"data_fiber", 'DateTime'>
}
    

// Custom InputTypes
/**
 * data_fiber findUnique
 */
export type data_fiberFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the data_fiber
   */
  select?: Prisma.data_fiberSelect<ExtArgs> | null
  /**
   * Omit specific fields from the data_fiber
   */
  omit?: Prisma.data_fiberOmit<ExtArgs> | null
  /**
   * Filter, which data_fiber to fetch.
   */
  where: Prisma.data_fiberWhereUniqueInput
}

/**
 * data_fiber findUniqueOrThrow
 */
export type data_fiberFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the data_fiber
   */
  select?: Prisma.data_fiberSelect<ExtArgs> | null
  /**
   * Omit specific fields from the data_fiber
   */
  omit?: Prisma.data_fiberOmit<ExtArgs> | null
  /**
   * Filter, which data_fiber to fetch.
   */
  where: Prisma.data_fiberWhereUniqueInput
}

/**
 * data_fiber findFirst
 */
export type data_fiberFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the data_fiber
   */
  select?: Prisma.data_fiberSelect<ExtArgs> | null
  /**
   * Omit specific fields from the data_fiber
   */
  omit?: Prisma.data_fiberOmit<ExtArgs> | null
  /**
   * Filter, which data_fiber to fetch.
   */
  where?: Prisma.data_fiberWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of data_fibers to fetch.
   */
  orderBy?: Prisma.data_fiberOrderByWithRelationInput | Prisma.data_fiberOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for data_fibers.
   */
  cursor?: Prisma.data_fiberWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` data_fibers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` data_fibers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of data_fibers.
   */
  distinct?: Prisma.Data_fiberScalarFieldEnum | Prisma.Data_fiberScalarFieldEnum[]
}

/**
 * data_fiber findFirstOrThrow
 */
export type data_fiberFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the data_fiber
   */
  select?: Prisma.data_fiberSelect<ExtArgs> | null
  /**
   * Omit specific fields from the data_fiber
   */
  omit?: Prisma.data_fiberOmit<ExtArgs> | null
  /**
   * Filter, which data_fiber to fetch.
   */
  where?: Prisma.data_fiberWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of data_fibers to fetch.
   */
  orderBy?: Prisma.data_fiberOrderByWithRelationInput | Prisma.data_fiberOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for data_fibers.
   */
  cursor?: Prisma.data_fiberWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` data_fibers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` data_fibers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of data_fibers.
   */
  distinct?: Prisma.Data_fiberScalarFieldEnum | Prisma.Data_fiberScalarFieldEnum[]
}

/**
 * data_fiber findMany
 */
export type data_fiberFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the data_fiber
   */
  select?: Prisma.data_fiberSelect<ExtArgs> | null
  /**
   * Omit specific fields from the data_fiber
   */
  omit?: Prisma.data_fiberOmit<ExtArgs> | null
  /**
   * Filter, which data_fibers to fetch.
   */
  where?: Prisma.data_fiberWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of data_fibers to fetch.
   */
  orderBy?: Prisma.data_fiberOrderByWithRelationInput | Prisma.data_fiberOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing data_fibers.
   */
  cursor?: Prisma.data_fiberWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` data_fibers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` data_fibers.
   */
  skip?: number
  distinct?: Prisma.Data_fiberScalarFieldEnum | Prisma.Data_fiberScalarFieldEnum[]
}

/**
 * data_fiber create
 */
export type data_fiberCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the data_fiber
   */
  select?: Prisma.data_fiberSelect<ExtArgs> | null
  /**
   * Omit specific fields from the data_fiber
   */
  omit?: Prisma.data_fiberOmit<ExtArgs> | null
  /**
   * The data needed to create a data_fiber.
   */
  data: Prisma.XOR<Prisma.data_fiberCreateInput, Prisma.data_fiberUncheckedCreateInput>
}

/**
 * data_fiber createMany
 */
export type data_fiberCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many data_fibers.
   */
  data: Prisma.data_fiberCreateManyInput | Prisma.data_fiberCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * data_fiber createManyAndReturn
 */
export type data_fiberCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the data_fiber
   */
  select?: Prisma.data_fiberSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the data_fiber
   */
  omit?: Prisma.data_fiberOmit<ExtArgs> | null
  /**
   * The data used to create many data_fibers.
   */
  data: Prisma.data_fiberCreateManyInput | Prisma.data_fiberCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * data_fiber update
 */
export type data_fiberUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the data_fiber
   */
  select?: Prisma.data_fiberSelect<ExtArgs> | null
  /**
   * Omit specific fields from the data_fiber
   */
  omit?: Prisma.data_fiberOmit<ExtArgs> | null
  /**
   * The data needed to update a data_fiber.
   */
  data: Prisma.XOR<Prisma.data_fiberUpdateInput, Prisma.data_fiberUncheckedUpdateInput>
  /**
   * Choose, which data_fiber to update.
   */
  where: Prisma.data_fiberWhereUniqueInput
}

/**
 * data_fiber updateMany
 */
export type data_fiberUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update data_fibers.
   */
  data: Prisma.XOR<Prisma.data_fiberUpdateManyMutationInput, Prisma.data_fiberUncheckedUpdateManyInput>
  /**
   * Filter which data_fibers to update
   */
  where?: Prisma.data_fiberWhereInput
  /**
   * Limit how many data_fibers to update.
   */
  limit?: number
}

/**
 * data_fiber updateManyAndReturn
 */
export type data_fiberUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the data_fiber
   */
  select?: Prisma.data_fiberSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the data_fiber
   */
  omit?: Prisma.data_fiberOmit<ExtArgs> | null
  /**
   * The data used to update data_fibers.
   */
  data: Prisma.XOR<Prisma.data_fiberUpdateManyMutationInput, Prisma.data_fiberUncheckedUpdateManyInput>
  /**
   * Filter which data_fibers to update
   */
  where?: Prisma.data_fiberWhereInput
  /**
   * Limit how many data_fibers to update.
   */
  limit?: number
}

/**
 * data_fiber upsert
 */
export type data_fiberUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the data_fiber
   */
  select?: Prisma.data_fiberSelect<ExtArgs> | null
  /**
   * Omit specific fields from the data_fiber
   */
  omit?: Prisma.data_fiberOmit<ExtArgs> | null
  /**
   * The filter to search for the data_fiber to update in case it exists.
   */
  where: Prisma.data_fiberWhereUniqueInput
  /**
   * In case the data_fiber found by the `where` argument doesn't exist, create a new data_fiber with this data.
   */
  create: Prisma.XOR<Prisma.data_fiberCreateInput, Prisma.data_fiberUncheckedCreateInput>
  /**
   * In case the data_fiber was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.data_fiberUpdateInput, Prisma.data_fiberUncheckedUpdateInput>
}

/**
 * data_fiber delete
 */
export type data_fiberDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the data_fiber
   */
  select?: Prisma.data_fiberSelect<ExtArgs> | null
  /**
   * Omit specific fields from the data_fiber
   */
  omit?: Prisma.data_fiberOmit<ExtArgs> | null
  /**
   * Filter which data_fiber to delete.
   */
  where: Prisma.data_fiberWhereUniqueInput
}

/**
 * data_fiber deleteMany
 */
export type data_fiberDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which data_fibers to delete
   */
  where?: Prisma.data_fiberWhereInput
  /**
   * Limit how many data_fibers to delete.
   */
  limit?: number
}

/**
 * data_fiber without action
 */
export type data_fiberDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the data_fiber
   */
  select?: Prisma.data_fiberSelect<ExtArgs> | null
  /**
   * Omit specific fields from the data_fiber
   */
  omit?: Prisma.data_fiberOmit<ExtArgs> | null
}
