
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `log_komplain` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model log_komplain
 * 
 */
export type log_komplainModel = runtime.Types.Result.DefaultSelection<Prisma.$log_komplainPayload>

export type AggregateLog_komplain = {
  _count: Log_komplainCountAggregateOutputType | null
  _avg: Log_komplainAvgAggregateOutputType | null
  _sum: Log_komplainSumAggregateOutputType | null
  _min: Log_komplainMinAggregateOutputType | null
  _max: Log_komplainMaxAggregateOutputType | null
}

export type Log_komplainAvgAggregateOutputType = {
  id: number | null
}

export type Log_komplainSumAggregateOutputType = {
  id: number | null
}

export type Log_komplainMinAggregateOutputType = {
  id: number | null
  tiket: string | null
  tanggal: string | null
  waktu: string | null
  nama: string | null
  kendala: string | null
  status: string | null
  action: string | null
  note: string | null
  pic: string | null
  last_updated: Date | null
  onu_sn: string | null
}

export type Log_komplainMaxAggregateOutputType = {
  id: number | null
  tiket: string | null
  tanggal: string | null
  waktu: string | null
  nama: string | null
  kendala: string | null
  status: string | null
  action: string | null
  note: string | null
  pic: string | null
  last_updated: Date | null
  onu_sn: string | null
}

export type Log_komplainCountAggregateOutputType = {
  id: number
  tiket: number
  tanggal: number
  waktu: number
  nama: number
  kendala: number
  status: number
  action: number
  note: number
  pic: number
  last_updated: number
  onu_sn: number
  _all: number
}


export type Log_komplainAvgAggregateInputType = {
  id?: true
}

export type Log_komplainSumAggregateInputType = {
  id?: true
}

export type Log_komplainMinAggregateInputType = {
  id?: true
  tiket?: true
  tanggal?: true
  waktu?: true
  nama?: true
  kendala?: true
  status?: true
  action?: true
  note?: true
  pic?: true
  last_updated?: true
  onu_sn?: true
}

export type Log_komplainMaxAggregateInputType = {
  id?: true
  tiket?: true
  tanggal?: true
  waktu?: true
  nama?: true
  kendala?: true
  status?: true
  action?: true
  note?: true
  pic?: true
  last_updated?: true
  onu_sn?: true
}

export type Log_komplainCountAggregateInputType = {
  id?: true
  tiket?: true
  tanggal?: true
  waktu?: true
  nama?: true
  kendala?: true
  status?: true
  action?: true
  note?: true
  pic?: true
  last_updated?: true
  onu_sn?: true
  _all?: true
}

export type Log_komplainAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which log_komplain to aggregate.
   */
  where?: Prisma.log_komplainWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of log_komplains to fetch.
   */
  orderBy?: Prisma.log_komplainOrderByWithRelationInput | Prisma.log_komplainOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.log_komplainWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` log_komplains from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` log_komplains.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned log_komplains
  **/
  _count?: true | Log_komplainCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Log_komplainAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Log_komplainSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Log_komplainMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Log_komplainMaxAggregateInputType
}

export type GetLog_komplainAggregateType<T extends Log_komplainAggregateArgs> = {
      [P in keyof T & keyof AggregateLog_komplain]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateLog_komplain[P]>
    : Prisma.GetScalarType<T[P], AggregateLog_komplain[P]>
}




export type log_komplainGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.log_komplainWhereInput
  orderBy?: Prisma.log_komplainOrderByWithAggregationInput | Prisma.log_komplainOrderByWithAggregationInput[]
  by: Prisma.Log_komplainScalarFieldEnum[] | Prisma.Log_komplainScalarFieldEnum
  having?: Prisma.log_komplainScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Log_komplainCountAggregateInputType | true
  _avg?: Log_komplainAvgAggregateInputType
  _sum?: Log_komplainSumAggregateInputType
  _min?: Log_komplainMinAggregateInputType
  _max?: Log_komplainMaxAggregateInputType
}

export type Log_komplainGroupByOutputType = {
  id: number
  tiket: string | null
  tanggal: string | null
  waktu: string | null
  nama: string | null
  kendala: string | null
  status: string | null
  action: string | null
  note: string | null
  pic: string | null
  last_updated: Date | null
  onu_sn: string | null
  _count: Log_komplainCountAggregateOutputType | null
  _avg: Log_komplainAvgAggregateOutputType | null
  _sum: Log_komplainSumAggregateOutputType | null
  _min: Log_komplainMinAggregateOutputType | null
  _max: Log_komplainMaxAggregateOutputType | null
}

type GetLog_komplainGroupByPayload<T extends log_komplainGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Log_komplainGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Log_komplainGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Log_komplainGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Log_komplainGroupByOutputType[P]>
      }
    >
  >



export type log_komplainWhereInput = {
  AND?: Prisma.log_komplainWhereInput | Prisma.log_komplainWhereInput[]
  OR?: Prisma.log_komplainWhereInput[]
  NOT?: Prisma.log_komplainWhereInput | Prisma.log_komplainWhereInput[]
  id?: Prisma.IntFilter<"log_komplain"> | number
  tiket?: Prisma.StringNullableFilter<"log_komplain"> | string | null
  tanggal?: Prisma.StringNullableFilter<"log_komplain"> | string | null
  waktu?: Prisma.StringNullableFilter<"log_komplain"> | string | null
  nama?: Prisma.StringNullableFilter<"log_komplain"> | string | null
  kendala?: Prisma.StringNullableFilter<"log_komplain"> | string | null
  status?: Prisma.StringNullableFilter<"log_komplain"> | string | null
  action?: Prisma.StringNullableFilter<"log_komplain"> | string | null
  note?: Prisma.StringNullableFilter<"log_komplain"> | string | null
  pic?: Prisma.StringNullableFilter<"log_komplain"> | string | null
  last_updated?: Prisma.DateTimeNullableFilter<"log_komplain"> | Date | string | null
  onu_sn?: Prisma.StringNullableFilter<"log_komplain"> | string | null
}

export type log_komplainOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  tiket?: Prisma.SortOrderInput | Prisma.SortOrder
  tanggal?: Prisma.SortOrderInput | Prisma.SortOrder
  waktu?: Prisma.SortOrderInput | Prisma.SortOrder
  nama?: Prisma.SortOrderInput | Prisma.SortOrder
  kendala?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrderInput | Prisma.SortOrder
  action?: Prisma.SortOrderInput | Prisma.SortOrder
  note?: Prisma.SortOrderInput | Prisma.SortOrder
  pic?: Prisma.SortOrderInput | Prisma.SortOrder
  last_updated?: Prisma.SortOrderInput | Prisma.SortOrder
  onu_sn?: Prisma.SortOrderInput | Prisma.SortOrder
}

export type log_komplainWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  tiket?: string
  AND?: Prisma.log_komplainWhereInput | Prisma.log_komplainWhereInput[]
  OR?: Prisma.log_komplainWhereInput[]
  NOT?: Prisma.log_komplainWhereInput | Prisma.log_komplainWhereInput[]
  tanggal?: Prisma.StringNullableFilter<"log_komplain"> | string | null
  waktu?: Prisma.StringNullableFilter<"log_komplain"> | string | null
  nama?: Prisma.StringNullableFilter<"log_komplain"> | string | null
  kendala?: Prisma.StringNullableFilter<"log_komplain"> | string | null
  status?: Prisma.StringNullableFilter<"log_komplain"> | string | null
  action?: Prisma.StringNullableFilter<"log_komplain"> | string | null
  note?: Prisma.StringNullableFilter<"log_komplain"> | string | null
  pic?: Prisma.StringNullableFilter<"log_komplain"> | string | null
  last_updated?: Prisma.DateTimeNullableFilter<"log_komplain"> | Date | string | null
  onu_sn?: Prisma.StringNullableFilter<"log_komplain"> | string | null
}, "id" | "tiket">

export type log_komplainOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  tiket?: Prisma.SortOrderInput | Prisma.SortOrder
  tanggal?: Prisma.SortOrderInput | Prisma.SortOrder
  waktu?: Prisma.SortOrderInput | Prisma.SortOrder
  nama?: Prisma.SortOrderInput | Prisma.SortOrder
  kendala?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrderInput | Prisma.SortOrder
  action?: Prisma.SortOrderInput | Prisma.SortOrder
  note?: Prisma.SortOrderInput | Prisma.SortOrder
  pic?: Prisma.SortOrderInput | Prisma.SortOrder
  last_updated?: Prisma.SortOrderInput | Prisma.SortOrder
  onu_sn?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.log_komplainCountOrderByAggregateInput
  _avg?: Prisma.log_komplainAvgOrderByAggregateInput
  _max?: Prisma.log_komplainMaxOrderByAggregateInput
  _min?: Prisma.log_komplainMinOrderByAggregateInput
  _sum?: Prisma.log_komplainSumOrderByAggregateInput
}

export type log_komplainScalarWhereWithAggregatesInput = {
  AND?: Prisma.log_komplainScalarWhereWithAggregatesInput | Prisma.log_komplainScalarWhereWithAggregatesInput[]
  OR?: Prisma.log_komplainScalarWhereWithAggregatesInput[]
  NOT?: Prisma.log_komplainScalarWhereWithAggregatesInput | Prisma.log_komplainScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"log_komplain"> | number
  tiket?: Prisma.StringNullableWithAggregatesFilter<"log_komplain"> | string | null
  tanggal?: Prisma.StringNullableWithAggregatesFilter<"log_komplain"> | string | null
  waktu?: Prisma.StringNullableWithAggregatesFilter<"log_komplain"> | string | null
  nama?: Prisma.StringNullableWithAggregatesFilter<"log_komplain"> | string | null
  kendala?: Prisma.StringNullableWithAggregatesFilter<"log_komplain"> | string | null
  status?: Prisma.StringNullableWithAggregatesFilter<"log_komplain"> | string | null
  action?: Prisma.StringNullableWithAggregatesFilter<"log_komplain"> | string | null
  note?: Prisma.StringNullableWithAggregatesFilter<"log_komplain"> | string | null
  pic?: Prisma.StringNullableWithAggregatesFilter<"log_komplain"> | string | null
  last_updated?: Prisma.DateTimeNullableWithAggregatesFilter<"log_komplain"> | Date | string | null
  onu_sn?: Prisma.StringNullableWithAggregatesFilter<"log_komplain"> | string | null
}

export type log_komplainCreateInput = {
  tiket?: string | null
  tanggal?: string | null
  waktu?: string | null
  nama?: string | null
  kendala?: string | null
  status?: string | null
  action?: string | null
  note?: string | null
  pic?: string | null
  last_updated?: Date | string | null
  onu_sn?: string | null
}

export type log_komplainUncheckedCreateInput = {
  id?: number
  tiket?: string | null
  tanggal?: string | null
  waktu?: string | null
  nama?: string | null
  kendala?: string | null
  status?: string | null
  action?: string | null
  note?: string | null
  pic?: string | null
  last_updated?: Date | string | null
  onu_sn?: string | null
}

export type log_komplainUpdateInput = {
  tiket?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tanggal?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  waktu?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  nama?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  kendala?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  action?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pic?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  last_updated?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  onu_sn?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type log_komplainUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  tiket?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tanggal?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  waktu?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  nama?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  kendala?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  action?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pic?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  last_updated?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  onu_sn?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type log_komplainCreateManyInput = {
  id?: number
  tiket?: string | null
  tanggal?: string | null
  waktu?: string | null
  nama?: string | null
  kendala?: string | null
  status?: string | null
  action?: string | null
  note?: string | null
  pic?: string | null
  last_updated?: Date | string | null
  onu_sn?: string | null
}

export type log_komplainUpdateManyMutationInput = {
  tiket?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tanggal?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  waktu?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  nama?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  kendala?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  action?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pic?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  last_updated?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  onu_sn?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type log_komplainUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  tiket?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tanggal?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  waktu?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  nama?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  kendala?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  action?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pic?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  last_updated?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  onu_sn?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type log_komplainCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tiket?: Prisma.SortOrder
  tanggal?: Prisma.SortOrder
  waktu?: Prisma.SortOrder
  nama?: Prisma.SortOrder
  kendala?: Prisma.SortOrder
  status?: Prisma.SortOrder
  action?: Prisma.SortOrder
  note?: Prisma.SortOrder
  pic?: Prisma.SortOrder
  last_updated?: Prisma.SortOrder
  onu_sn?: Prisma.SortOrder
}

export type log_komplainAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type log_komplainMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tiket?: Prisma.SortOrder
  tanggal?: Prisma.SortOrder
  waktu?: Prisma.SortOrder
  nama?: Prisma.SortOrder
  kendala?: Prisma.SortOrder
  status?: Prisma.SortOrder
  action?: Prisma.SortOrder
  note?: Prisma.SortOrder
  pic?: Prisma.SortOrder
  last_updated?: Prisma.SortOrder
  onu_sn?: Prisma.SortOrder
}

export type log_komplainMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tiket?: Prisma.SortOrder
  tanggal?: Prisma.SortOrder
  waktu?: Prisma.SortOrder
  nama?: Prisma.SortOrder
  kendala?: Prisma.SortOrder
  status?: Prisma.SortOrder
  action?: Prisma.SortOrder
  note?: Prisma.SortOrder
  pic?: Prisma.SortOrder
  last_updated?: Prisma.SortOrder
  onu_sn?: Prisma.SortOrder
}

export type log_komplainSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}



export type log_komplainSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  tiket?: boolean
  tanggal?: boolean
  waktu?: boolean
  nama?: boolean
  kendala?: boolean
  status?: boolean
  action?: boolean
  note?: boolean
  pic?: boolean
  last_updated?: boolean
  onu_sn?: boolean
}, ExtArgs["result"]["log_komplain"]>

export type log_komplainSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  tiket?: boolean
  tanggal?: boolean
  waktu?: boolean
  nama?: boolean
  kendala?: boolean
  status?: boolean
  action?: boolean
  note?: boolean
  pic?: boolean
  last_updated?: boolean
  onu_sn?: boolean
}, ExtArgs["result"]["log_komplain"]>

export type log_komplainSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  tiket?: boolean
  tanggal?: boolean
  waktu?: boolean
  nama?: boolean
  kendala?: boolean
  status?: boolean
  action?: boolean
  note?: boolean
  pic?: boolean
  last_updated?: boolean
  onu_sn?: boolean
}, ExtArgs["result"]["log_komplain"]>

export type log_komplainSelectScalar = {
  id?: boolean
  tiket?: boolean
  tanggal?: boolean
  waktu?: boolean
  nama?: boolean
  kendala?: boolean
  status?: boolean
  action?: boolean
  note?: boolean
  pic?: boolean
  last_updated?: boolean
  onu_sn?: boolean
}

export type log_komplainOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "tiket" | "tanggal" | "waktu" | "nama" | "kendala" | "status" | "action" | "note" | "pic" | "last_updated" | "onu_sn", ExtArgs["result"]["log_komplain"]>

export type $log_komplainPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "log_komplain"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    tiket: string | null
    tanggal: string | null
    waktu: string | null
    nama: string | null
    kendala: string | null
    status: string | null
    action: string | null
    note: string | null
    pic: string | null
    last_updated: Date | null
    onu_sn: string | null
  }, ExtArgs["result"]["log_komplain"]>
  composites: {}
}

export type log_komplainGetPayload<S extends boolean | null | undefined | log_komplainDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$log_komplainPayload, S>

export type log_komplainCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<log_komplainFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Log_komplainCountAggregateInputType | true
  }

export interface log_komplainDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['log_komplain'], meta: { name: 'log_komplain' } }
  /**
   * Find zero or one Log_komplain that matches the filter.
   * @param {log_komplainFindUniqueArgs} args - Arguments to find a Log_komplain
   * @example
   * // Get one Log_komplain
   * const log_komplain = await prisma.log_komplain.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends log_komplainFindUniqueArgs>(args: Prisma.SelectSubset<T, log_komplainFindUniqueArgs<ExtArgs>>): Prisma.Prisma__log_komplainClient<runtime.Types.Result.GetResult<Prisma.$log_komplainPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Log_komplain that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {log_komplainFindUniqueOrThrowArgs} args - Arguments to find a Log_komplain
   * @example
   * // Get one Log_komplain
   * const log_komplain = await prisma.log_komplain.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends log_komplainFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, log_komplainFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__log_komplainClient<runtime.Types.Result.GetResult<Prisma.$log_komplainPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Log_komplain that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {log_komplainFindFirstArgs} args - Arguments to find a Log_komplain
   * @example
   * // Get one Log_komplain
   * const log_komplain = await prisma.log_komplain.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends log_komplainFindFirstArgs>(args?: Prisma.SelectSubset<T, log_komplainFindFirstArgs<ExtArgs>>): Prisma.Prisma__log_komplainClient<runtime.Types.Result.GetResult<Prisma.$log_komplainPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Log_komplain that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {log_komplainFindFirstOrThrowArgs} args - Arguments to find a Log_komplain
   * @example
   * // Get one Log_komplain
   * const log_komplain = await prisma.log_komplain.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends log_komplainFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, log_komplainFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__log_komplainClient<runtime.Types.Result.GetResult<Prisma.$log_komplainPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Log_komplains that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {log_komplainFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Log_komplains
   * const log_komplains = await prisma.log_komplain.findMany()
   * 
   * // Get first 10 Log_komplains
   * const log_komplains = await prisma.log_komplain.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const log_komplainWithIdOnly = await prisma.log_komplain.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends log_komplainFindManyArgs>(args?: Prisma.SelectSubset<T, log_komplainFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$log_komplainPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Log_komplain.
   * @param {log_komplainCreateArgs} args - Arguments to create a Log_komplain.
   * @example
   * // Create one Log_komplain
   * const Log_komplain = await prisma.log_komplain.create({
   *   data: {
   *     // ... data to create a Log_komplain
   *   }
   * })
   * 
   */
  create<T extends log_komplainCreateArgs>(args: Prisma.SelectSubset<T, log_komplainCreateArgs<ExtArgs>>): Prisma.Prisma__log_komplainClient<runtime.Types.Result.GetResult<Prisma.$log_komplainPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Log_komplains.
   * @param {log_komplainCreateManyArgs} args - Arguments to create many Log_komplains.
   * @example
   * // Create many Log_komplains
   * const log_komplain = await prisma.log_komplain.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends log_komplainCreateManyArgs>(args?: Prisma.SelectSubset<T, log_komplainCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Log_komplains and returns the data saved in the database.
   * @param {log_komplainCreateManyAndReturnArgs} args - Arguments to create many Log_komplains.
   * @example
   * // Create many Log_komplains
   * const log_komplain = await prisma.log_komplain.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Log_komplains and only return the `id`
   * const log_komplainWithIdOnly = await prisma.log_komplain.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends log_komplainCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, log_komplainCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$log_komplainPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Log_komplain.
   * @param {log_komplainDeleteArgs} args - Arguments to delete one Log_komplain.
   * @example
   * // Delete one Log_komplain
   * const Log_komplain = await prisma.log_komplain.delete({
   *   where: {
   *     // ... filter to delete one Log_komplain
   *   }
   * })
   * 
   */
  delete<T extends log_komplainDeleteArgs>(args: Prisma.SelectSubset<T, log_komplainDeleteArgs<ExtArgs>>): Prisma.Prisma__log_komplainClient<runtime.Types.Result.GetResult<Prisma.$log_komplainPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Log_komplain.
   * @param {log_komplainUpdateArgs} args - Arguments to update one Log_komplain.
   * @example
   * // Update one Log_komplain
   * const log_komplain = await prisma.log_komplain.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends log_komplainUpdateArgs>(args: Prisma.SelectSubset<T, log_komplainUpdateArgs<ExtArgs>>): Prisma.Prisma__log_komplainClient<runtime.Types.Result.GetResult<Prisma.$log_komplainPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Log_komplains.
   * @param {log_komplainDeleteManyArgs} args - Arguments to filter Log_komplains to delete.
   * @example
   * // Delete a few Log_komplains
   * const { count } = await prisma.log_komplain.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends log_komplainDeleteManyArgs>(args?: Prisma.SelectSubset<T, log_komplainDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Log_komplains.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {log_komplainUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Log_komplains
   * const log_komplain = await prisma.log_komplain.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends log_komplainUpdateManyArgs>(args: Prisma.SelectSubset<T, log_komplainUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Log_komplains and returns the data updated in the database.
   * @param {log_komplainUpdateManyAndReturnArgs} args - Arguments to update many Log_komplains.
   * @example
   * // Update many Log_komplains
   * const log_komplain = await prisma.log_komplain.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Log_komplains and only return the `id`
   * const log_komplainWithIdOnly = await prisma.log_komplain.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends log_komplainUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, log_komplainUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$log_komplainPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Log_komplain.
   * @param {log_komplainUpsertArgs} args - Arguments to update or create a Log_komplain.
   * @example
   * // Update or create a Log_komplain
   * const log_komplain = await prisma.log_komplain.upsert({
   *   create: {
   *     // ... data to create a Log_komplain
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Log_komplain we want to update
   *   }
   * })
   */
  upsert<T extends log_komplainUpsertArgs>(args: Prisma.SelectSubset<T, log_komplainUpsertArgs<ExtArgs>>): Prisma.Prisma__log_komplainClient<runtime.Types.Result.GetResult<Prisma.$log_komplainPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Log_komplains.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {log_komplainCountArgs} args - Arguments to filter Log_komplains to count.
   * @example
   * // Count the number of Log_komplains
   * const count = await prisma.log_komplain.count({
   *   where: {
   *     // ... the filter for the Log_komplains we want to count
   *   }
   * })
  **/
  count<T extends log_komplainCountArgs>(
    args?: Prisma.Subset<T, log_komplainCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Log_komplainCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Log_komplain.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Log_komplainAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Log_komplainAggregateArgs>(args: Prisma.Subset<T, Log_komplainAggregateArgs>): Prisma.PrismaPromise<GetLog_komplainAggregateType<T>>

  /**
   * Group by Log_komplain.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {log_komplainGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends log_komplainGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: log_komplainGroupByArgs['orderBy'] }
      : { orderBy?: log_komplainGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, log_komplainGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetLog_komplainGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the log_komplain model
 */
readonly fields: log_komplainFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for log_komplain.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__log_komplainClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the log_komplain model
 */
export interface log_komplainFieldRefs {
  readonly id: Prisma.FieldRef<"log_komplain", 'Int'>
  readonly tiket: Prisma.FieldRef<"log_komplain", 'String'>
  readonly tanggal: Prisma.FieldRef<"log_komplain", 'String'>
  readonly waktu: Prisma.FieldRef<"log_komplain", 'String'>
  readonly nama: Prisma.FieldRef<"log_komplain", 'String'>
  readonly kendala: Prisma.FieldRef<"log_komplain", 'String'>
  readonly status: Prisma.FieldRef<"log_komplain", 'String'>
  readonly action: Prisma.FieldRef<"log_komplain", 'String'>
  readonly note: Prisma.FieldRef<"log_komplain", 'String'>
  readonly pic: Prisma.FieldRef<"log_komplain", 'String'>
  readonly last_updated: Prisma.FieldRef<"log_komplain", 'DateTime'>
  readonly onu_sn: Prisma.FieldRef<"log_komplain", 'String'>
}
    

// Custom InputTypes
/**
 * log_komplain findUnique
 */
export type log_komplainFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the log_komplain
   */
  select?: Prisma.log_komplainSelect<ExtArgs> | null
  /**
   * Omit specific fields from the log_komplain
   */
  omit?: Prisma.log_komplainOmit<ExtArgs> | null
  /**
   * Filter, which log_komplain to fetch.
   */
  where: Prisma.log_komplainWhereUniqueInput
}

/**
 * log_komplain findUniqueOrThrow
 */
export type log_komplainFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the log_komplain
   */
  select?: Prisma.log_komplainSelect<ExtArgs> | null
  /**
   * Omit specific fields from the log_komplain
   */
  omit?: Prisma.log_komplainOmit<ExtArgs> | null
  /**
   * Filter, which log_komplain to fetch.
   */
  where: Prisma.log_komplainWhereUniqueInput
}

/**
 * log_komplain findFirst
 */
export type log_komplainFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the log_komplain
   */
  select?: Prisma.log_komplainSelect<ExtArgs> | null
  /**
   * Omit specific fields from the log_komplain
   */
  omit?: Prisma.log_komplainOmit<ExtArgs> | null
  /**
   * Filter, which log_komplain to fetch.
   */
  where?: Prisma.log_komplainWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of log_komplains to fetch.
   */
  orderBy?: Prisma.log_komplainOrderByWithRelationInput | Prisma.log_komplainOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for log_komplains.
   */
  cursor?: Prisma.log_komplainWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` log_komplains from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` log_komplains.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of log_komplains.
   */
  distinct?: Prisma.Log_komplainScalarFieldEnum | Prisma.Log_komplainScalarFieldEnum[]
}

/**
 * log_komplain findFirstOrThrow
 */
export type log_komplainFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the log_komplain
   */
  select?: Prisma.log_komplainSelect<ExtArgs> | null
  /**
   * Omit specific fields from the log_komplain
   */
  omit?: Prisma.log_komplainOmit<ExtArgs> | null
  /**
   * Filter, which log_komplain to fetch.
   */
  where?: Prisma.log_komplainWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of log_komplains to fetch.
   */
  orderBy?: Prisma.log_komplainOrderByWithRelationInput | Prisma.log_komplainOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for log_komplains.
   */
  cursor?: Prisma.log_komplainWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` log_komplains from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` log_komplains.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of log_komplains.
   */
  distinct?: Prisma.Log_komplainScalarFieldEnum | Prisma.Log_komplainScalarFieldEnum[]
}

/**
 * log_komplain findMany
 */
export type log_komplainFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the log_komplain
   */
  select?: Prisma.log_komplainSelect<ExtArgs> | null
  /**
   * Omit specific fields from the log_komplain
   */
  omit?: Prisma.log_komplainOmit<ExtArgs> | null
  /**
   * Filter, which log_komplains to fetch.
   */
  where?: Prisma.log_komplainWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of log_komplains to fetch.
   */
  orderBy?: Prisma.log_komplainOrderByWithRelationInput | Prisma.log_komplainOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing log_komplains.
   */
  cursor?: Prisma.log_komplainWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` log_komplains from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` log_komplains.
   */
  skip?: number
  distinct?: Prisma.Log_komplainScalarFieldEnum | Prisma.Log_komplainScalarFieldEnum[]
}

/**
 * log_komplain create
 */
export type log_komplainCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the log_komplain
   */
  select?: Prisma.log_komplainSelect<ExtArgs> | null
  /**
   * Omit specific fields from the log_komplain
   */
  omit?: Prisma.log_komplainOmit<ExtArgs> | null
  /**
   * The data needed to create a log_komplain.
   */
  data?: Prisma.XOR<Prisma.log_komplainCreateInput, Prisma.log_komplainUncheckedCreateInput>
}

/**
 * log_komplain createMany
 */
export type log_komplainCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many log_komplains.
   */
  data: Prisma.log_komplainCreateManyInput | Prisma.log_komplainCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * log_komplain createManyAndReturn
 */
export type log_komplainCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the log_komplain
   */
  select?: Prisma.log_komplainSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the log_komplain
   */
  omit?: Prisma.log_komplainOmit<ExtArgs> | null
  /**
   * The data used to create many log_komplains.
   */
  data: Prisma.log_komplainCreateManyInput | Prisma.log_komplainCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * log_komplain update
 */
export type log_komplainUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the log_komplain
   */
  select?: Prisma.log_komplainSelect<ExtArgs> | null
  /**
   * Omit specific fields from the log_komplain
   */
  omit?: Prisma.log_komplainOmit<ExtArgs> | null
  /**
   * The data needed to update a log_komplain.
   */
  data: Prisma.XOR<Prisma.log_komplainUpdateInput, Prisma.log_komplainUncheckedUpdateInput>
  /**
   * Choose, which log_komplain to update.
   */
  where: Prisma.log_komplainWhereUniqueInput
}

/**
 * log_komplain updateMany
 */
export type log_komplainUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update log_komplains.
   */
  data: Prisma.XOR<Prisma.log_komplainUpdateManyMutationInput, Prisma.log_komplainUncheckedUpdateManyInput>
  /**
   * Filter which log_komplains to update
   */
  where?: Prisma.log_komplainWhereInput
  /**
   * Limit how many log_komplains to update.
   */
  limit?: number
}

/**
 * log_komplain updateManyAndReturn
 */
export type log_komplainUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the log_komplain
   */
  select?: Prisma.log_komplainSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the log_komplain
   */
  omit?: Prisma.log_komplainOmit<ExtArgs> | null
  /**
   * The data used to update log_komplains.
   */
  data: Prisma.XOR<Prisma.log_komplainUpdateManyMutationInput, Prisma.log_komplainUncheckedUpdateManyInput>
  /**
   * Filter which log_komplains to update
   */
  where?: Prisma.log_komplainWhereInput
  /**
   * Limit how many log_komplains to update.
   */
  limit?: number
}

/**
 * log_komplain upsert
 */
export type log_komplainUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the log_komplain
   */
  select?: Prisma.log_komplainSelect<ExtArgs> | null
  /**
   * Omit specific fields from the log_komplain
   */
  omit?: Prisma.log_komplainOmit<ExtArgs> | null
  /**
   * The filter to search for the log_komplain to update in case it exists.
   */
  where: Prisma.log_komplainWhereUniqueInput
  /**
   * In case the log_komplain found by the `where` argument doesn't exist, create a new log_komplain with this data.
   */
  create: Prisma.XOR<Prisma.log_komplainCreateInput, Prisma.log_komplainUncheckedCreateInput>
  /**
   * In case the log_komplain was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.log_komplainUpdateInput, Prisma.log_komplainUncheckedUpdateInput>
}

/**
 * log_komplain delete
 */
export type log_komplainDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the log_komplain
   */
  select?: Prisma.log_komplainSelect<ExtArgs> | null
  /**
   * Omit specific fields from the log_komplain
   */
  omit?: Prisma.log_komplainOmit<ExtArgs> | null
  /**
   * Filter which log_komplain to delete.
   */
  where: Prisma.log_komplainWhereUniqueInput
}

/**
 * log_komplain deleteMany
 */
export type log_komplainDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which log_komplains to delete
   */
  where?: Prisma.log_komplainWhereInput
  /**
   * Limit how many log_komplains to delete.
   */
  limit?: number
}

/**
 * log_komplain without action
 */
export type log_komplainDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the log_komplain
   */
  select?: Prisma.log_komplainSelect<ExtArgs> | null
  /**
   * Omit specific fields from the log_komplain
   */
  omit?: Prisma.log_komplainOmit<ExtArgs> | null
}
