
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `snmp` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model snmp
 * 
 */
export type snmpModel = runtime.Types.Result.DefaultSelection<Prisma.$snmpPayload>

export type AggregateSnmp = {
  _count: SnmpCountAggregateOutputType | null
  _avg: SnmpAvgAggregateOutputType | null
  _sum: SnmpSumAggregateOutputType | null
  _min: SnmpMinAggregateOutputType | null
  _max: SnmpMaxAggregateOutputType | null
}

export type SnmpAvgAggregateOutputType = {
  rx_power_dbm: number | null
}

export type SnmpSumAggregateOutputType = {
  rx_power_dbm: number | null
}

export type SnmpMinAggregateOutputType = {
  olt_name: string | null
  interface: string | null
  name: string | null
  address: string | null
  sn: string | null
  modem_type: string | null
  status: string | null
  last_uptime: string | null
  rx_power_dbm: number | null
  rx_power_str: string | null
  raw_ifindex: string | null
  raw_onuid: string | null
  last_updated: Date | null
}

export type SnmpMaxAggregateOutputType = {
  olt_name: string | null
  interface: string | null
  name: string | null
  address: string | null
  sn: string | null
  modem_type: string | null
  status: string | null
  last_uptime: string | null
  rx_power_dbm: number | null
  rx_power_str: string | null
  raw_ifindex: string | null
  raw_onuid: string | null
  last_updated: Date | null
}

export type SnmpCountAggregateOutputType = {
  olt_name: number
  interface: number
  name: number
  address: number
  sn: number
  modem_type: number
  status: number
  last_uptime: number
  rx_power_dbm: number
  rx_power_str: number
  raw_ifindex: number
  raw_onuid: number
  last_updated: number
  _all: number
}


export type SnmpAvgAggregateInputType = {
  rx_power_dbm?: true
}

export type SnmpSumAggregateInputType = {
  rx_power_dbm?: true
}

export type SnmpMinAggregateInputType = {
  olt_name?: true
  interface?: true
  name?: true
  address?: true
  sn?: true
  modem_type?: true
  status?: true
  last_uptime?: true
  rx_power_dbm?: true
  rx_power_str?: true
  raw_ifindex?: true
  raw_onuid?: true
  last_updated?: true
}

export type SnmpMaxAggregateInputType = {
  olt_name?: true
  interface?: true
  name?: true
  address?: true
  sn?: true
  modem_type?: true
  status?: true
  last_uptime?: true
  rx_power_dbm?: true
  rx_power_str?: true
  raw_ifindex?: true
  raw_onuid?: true
  last_updated?: true
}

export type SnmpCountAggregateInputType = {
  olt_name?: true
  interface?: true
  name?: true
  address?: true
  sn?: true
  modem_type?: true
  status?: true
  last_uptime?: true
  rx_power_dbm?: true
  rx_power_str?: true
  raw_ifindex?: true
  raw_onuid?: true
  last_updated?: true
  _all?: true
}

export type SnmpAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which snmp to aggregate.
   */
  where?: Prisma.snmpWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of snmps to fetch.
   */
  orderBy?: Prisma.snmpOrderByWithRelationInput | Prisma.snmpOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.snmpWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` snmps from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` snmps.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned snmps
  **/
  _count?: true | SnmpCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: SnmpAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: SnmpSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SnmpMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SnmpMaxAggregateInputType
}

export type GetSnmpAggregateType<T extends SnmpAggregateArgs> = {
      [P in keyof T & keyof AggregateSnmp]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSnmp[P]>
    : Prisma.GetScalarType<T[P], AggregateSnmp[P]>
}




export type snmpGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.snmpWhereInput
  orderBy?: Prisma.snmpOrderByWithAggregationInput | Prisma.snmpOrderByWithAggregationInput[]
  by: Prisma.SnmpScalarFieldEnum[] | Prisma.SnmpScalarFieldEnum
  having?: Prisma.snmpScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SnmpCountAggregateInputType | true
  _avg?: SnmpAvgAggregateInputType
  _sum?: SnmpSumAggregateInputType
  _min?: SnmpMinAggregateInputType
  _max?: SnmpMaxAggregateInputType
}

export type SnmpGroupByOutputType = {
  olt_name: string
  interface: string
  name: string | null
  address: string | null
  sn: string | null
  modem_type: string | null
  status: string | null
  last_uptime: string | null
  rx_power_dbm: number | null
  rx_power_str: string | null
  raw_ifindex: string | null
  raw_onuid: string | null
  last_updated: Date | null
  _count: SnmpCountAggregateOutputType | null
  _avg: SnmpAvgAggregateOutputType | null
  _sum: SnmpSumAggregateOutputType | null
  _min: SnmpMinAggregateOutputType | null
  _max: SnmpMaxAggregateOutputType | null
}

type GetSnmpGroupByPayload<T extends snmpGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SnmpGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SnmpGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SnmpGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SnmpGroupByOutputType[P]>
      }
    >
  >



export type snmpWhereInput = {
  AND?: Prisma.snmpWhereInput | Prisma.snmpWhereInput[]
  OR?: Prisma.snmpWhereInput[]
  NOT?: Prisma.snmpWhereInput | Prisma.snmpWhereInput[]
  olt_name?: Prisma.StringFilter<"snmp"> | string
  interface?: Prisma.StringFilter<"snmp"> | string
  name?: Prisma.StringNullableFilter<"snmp"> | string | null
  address?: Prisma.StringNullableFilter<"snmp"> | string | null
  sn?: Prisma.StringNullableFilter<"snmp"> | string | null
  modem_type?: Prisma.StringNullableFilter<"snmp"> | string | null
  status?: Prisma.StringNullableFilter<"snmp"> | string | null
  last_uptime?: Prisma.StringNullableFilter<"snmp"> | string | null
  rx_power_dbm?: Prisma.FloatNullableFilter<"snmp"> | number | null
  rx_power_str?: Prisma.StringNullableFilter<"snmp"> | string | null
  raw_ifindex?: Prisma.StringNullableFilter<"snmp"> | string | null
  raw_onuid?: Prisma.StringNullableFilter<"snmp"> | string | null
  last_updated?: Prisma.DateTimeNullableFilter<"snmp"> | Date | string | null
}

export type snmpOrderByWithRelationInput = {
  olt_name?: Prisma.SortOrder
  interface?: Prisma.SortOrder
  name?: Prisma.SortOrderInput | Prisma.SortOrder
  address?: Prisma.SortOrderInput | Prisma.SortOrder
  sn?: Prisma.SortOrderInput | Prisma.SortOrder
  modem_type?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrderInput | Prisma.SortOrder
  last_uptime?: Prisma.SortOrderInput | Prisma.SortOrder
  rx_power_dbm?: Prisma.SortOrderInput | Prisma.SortOrder
  rx_power_str?: Prisma.SortOrderInput | Prisma.SortOrder
  raw_ifindex?: Prisma.SortOrderInput | Prisma.SortOrder
  raw_onuid?: Prisma.SortOrderInput | Prisma.SortOrder
  last_updated?: Prisma.SortOrderInput | Prisma.SortOrder
}

export type snmpWhereUniqueInput = Prisma.AtLeast<{
  olt_name_interface?: Prisma.snmpOlt_nameInterfaceCompoundUniqueInput
  AND?: Prisma.snmpWhereInput | Prisma.snmpWhereInput[]
  OR?: Prisma.snmpWhereInput[]
  NOT?: Prisma.snmpWhereInput | Prisma.snmpWhereInput[]
  olt_name?: Prisma.StringFilter<"snmp"> | string
  interface?: Prisma.StringFilter<"snmp"> | string
  name?: Prisma.StringNullableFilter<"snmp"> | string | null
  address?: Prisma.StringNullableFilter<"snmp"> | string | null
  sn?: Prisma.StringNullableFilter<"snmp"> | string | null
  modem_type?: Prisma.StringNullableFilter<"snmp"> | string | null
  status?: Prisma.StringNullableFilter<"snmp"> | string | null
  last_uptime?: Prisma.StringNullableFilter<"snmp"> | string | null
  rx_power_dbm?: Prisma.FloatNullableFilter<"snmp"> | number | null
  rx_power_str?: Prisma.StringNullableFilter<"snmp"> | string | null
  raw_ifindex?: Prisma.StringNullableFilter<"snmp"> | string | null
  raw_onuid?: Prisma.StringNullableFilter<"snmp"> | string | null
  last_updated?: Prisma.DateTimeNullableFilter<"snmp"> | Date | string | null
}, "olt_name_interface">

export type snmpOrderByWithAggregationInput = {
  olt_name?: Prisma.SortOrder
  interface?: Prisma.SortOrder
  name?: Prisma.SortOrderInput | Prisma.SortOrder
  address?: Prisma.SortOrderInput | Prisma.SortOrder
  sn?: Prisma.SortOrderInput | Prisma.SortOrder
  modem_type?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrderInput | Prisma.SortOrder
  last_uptime?: Prisma.SortOrderInput | Prisma.SortOrder
  rx_power_dbm?: Prisma.SortOrderInput | Prisma.SortOrder
  rx_power_str?: Prisma.SortOrderInput | Prisma.SortOrder
  raw_ifindex?: Prisma.SortOrderInput | Prisma.SortOrder
  raw_onuid?: Prisma.SortOrderInput | Prisma.SortOrder
  last_updated?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.snmpCountOrderByAggregateInput
  _avg?: Prisma.snmpAvgOrderByAggregateInput
  _max?: Prisma.snmpMaxOrderByAggregateInput
  _min?: Prisma.snmpMinOrderByAggregateInput
  _sum?: Prisma.snmpSumOrderByAggregateInput
}

export type snmpScalarWhereWithAggregatesInput = {
  AND?: Prisma.snmpScalarWhereWithAggregatesInput | Prisma.snmpScalarWhereWithAggregatesInput[]
  OR?: Prisma.snmpScalarWhereWithAggregatesInput[]
  NOT?: Prisma.snmpScalarWhereWithAggregatesInput | Prisma.snmpScalarWhereWithAggregatesInput[]
  olt_name?: Prisma.StringWithAggregatesFilter<"snmp"> | string
  interface?: Prisma.StringWithAggregatesFilter<"snmp"> | string
  name?: Prisma.StringNullableWithAggregatesFilter<"snmp"> | string | null
  address?: Prisma.StringNullableWithAggregatesFilter<"snmp"> | string | null
  sn?: Prisma.StringNullableWithAggregatesFilter<"snmp"> | string | null
  modem_type?: Prisma.StringNullableWithAggregatesFilter<"snmp"> | string | null
  status?: Prisma.StringNullableWithAggregatesFilter<"snmp"> | string | null
  last_uptime?: Prisma.StringNullableWithAggregatesFilter<"snmp"> | string | null
  rx_power_dbm?: Prisma.FloatNullableWithAggregatesFilter<"snmp"> | number | null
  rx_power_str?: Prisma.StringNullableWithAggregatesFilter<"snmp"> | string | null
  raw_ifindex?: Prisma.StringNullableWithAggregatesFilter<"snmp"> | string | null
  raw_onuid?: Prisma.StringNullableWithAggregatesFilter<"snmp"> | string | null
  last_updated?: Prisma.DateTimeNullableWithAggregatesFilter<"snmp"> | Date | string | null
}

export type snmpCreateInput = {
  olt_name: string
  interface: string
  name?: string | null
  address?: string | null
  sn?: string | null
  modem_type?: string | null
  status?: string | null
  last_uptime?: string | null
  rx_power_dbm?: number | null
  rx_power_str?: string | null
  raw_ifindex?: string | null
  raw_onuid?: string | null
  last_updated?: Date | string | null
}

export type snmpUncheckedCreateInput = {
  olt_name: string
  interface: string
  name?: string | null
  address?: string | null
  sn?: string | null
  modem_type?: string | null
  status?: string | null
  last_uptime?: string | null
  rx_power_dbm?: number | null
  rx_power_str?: string | null
  raw_ifindex?: string | null
  raw_onuid?: string | null
  last_updated?: Date | string | null
}

export type snmpUpdateInput = {
  olt_name?: Prisma.StringFieldUpdateOperationsInput | string
  interface?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sn?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  modem_type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  last_uptime?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rx_power_dbm?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  rx_power_str?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  raw_ifindex?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  raw_onuid?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  last_updated?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type snmpUncheckedUpdateInput = {
  olt_name?: Prisma.StringFieldUpdateOperationsInput | string
  interface?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sn?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  modem_type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  last_uptime?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rx_power_dbm?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  rx_power_str?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  raw_ifindex?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  raw_onuid?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  last_updated?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type snmpCreateManyInput = {
  olt_name: string
  interface: string
  name?: string | null
  address?: string | null
  sn?: string | null
  modem_type?: string | null
  status?: string | null
  last_uptime?: string | null
  rx_power_dbm?: number | null
  rx_power_str?: string | null
  raw_ifindex?: string | null
  raw_onuid?: string | null
  last_updated?: Date | string | null
}

export type snmpUpdateManyMutationInput = {
  olt_name?: Prisma.StringFieldUpdateOperationsInput | string
  interface?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sn?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  modem_type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  last_uptime?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rx_power_dbm?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  rx_power_str?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  raw_ifindex?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  raw_onuid?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  last_updated?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type snmpUncheckedUpdateManyInput = {
  olt_name?: Prisma.StringFieldUpdateOperationsInput | string
  interface?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sn?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  modem_type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  last_uptime?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rx_power_dbm?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  rx_power_str?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  raw_ifindex?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  raw_onuid?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  last_updated?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type snmpOlt_nameInterfaceCompoundUniqueInput = {
  olt_name: string
  interface: string
}

export type snmpCountOrderByAggregateInput = {
  olt_name?: Prisma.SortOrder
  interface?: Prisma.SortOrder
  name?: Prisma.SortOrder
  address?: Prisma.SortOrder
  sn?: Prisma.SortOrder
  modem_type?: Prisma.SortOrder
  status?: Prisma.SortOrder
  last_uptime?: Prisma.SortOrder
  rx_power_dbm?: Prisma.SortOrder
  rx_power_str?: Prisma.SortOrder
  raw_ifindex?: Prisma.SortOrder
  raw_onuid?: Prisma.SortOrder
  last_updated?: Prisma.SortOrder
}

export type snmpAvgOrderByAggregateInput = {
  rx_power_dbm?: Prisma.SortOrder
}

export type snmpMaxOrderByAggregateInput = {
  olt_name?: Prisma.SortOrder
  interface?: Prisma.SortOrder
  name?: Prisma.SortOrder
  address?: Prisma.SortOrder
  sn?: Prisma.SortOrder
  modem_type?: Prisma.SortOrder
  status?: Prisma.SortOrder
  last_uptime?: Prisma.SortOrder
  rx_power_dbm?: Prisma.SortOrder
  rx_power_str?: Prisma.SortOrder
  raw_ifindex?: Prisma.SortOrder
  raw_onuid?: Prisma.SortOrder
  last_updated?: Prisma.SortOrder
}

export type snmpMinOrderByAggregateInput = {
  olt_name?: Prisma.SortOrder
  interface?: Prisma.SortOrder
  name?: Prisma.SortOrder
  address?: Prisma.SortOrder
  sn?: Prisma.SortOrder
  modem_type?: Prisma.SortOrder
  status?: Prisma.SortOrder
  last_uptime?: Prisma.SortOrder
  rx_power_dbm?: Prisma.SortOrder
  rx_power_str?: Prisma.SortOrder
  raw_ifindex?: Prisma.SortOrder
  raw_onuid?: Prisma.SortOrder
  last_updated?: Prisma.SortOrder
}

export type snmpSumOrderByAggregateInput = {
  rx_power_dbm?: Prisma.SortOrder
}

export type NullableFloatFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}



export type snmpSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  olt_name?: boolean
  interface?: boolean
  name?: boolean
  address?: boolean
  sn?: boolean
  modem_type?: boolean
  status?: boolean
  last_uptime?: boolean
  rx_power_dbm?: boolean
  rx_power_str?: boolean
  raw_ifindex?: boolean
  raw_onuid?: boolean
  last_updated?: boolean
}, ExtArgs["result"]["snmp"]>

export type snmpSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  olt_name?: boolean
  interface?: boolean
  name?: boolean
  address?: boolean
  sn?: boolean
  modem_type?: boolean
  status?: boolean
  last_uptime?: boolean
  rx_power_dbm?: boolean
  rx_power_str?: boolean
  raw_ifindex?: boolean
  raw_onuid?: boolean
  last_updated?: boolean
}, ExtArgs["result"]["snmp"]>

export type snmpSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  olt_name?: boolean
  interface?: boolean
  name?: boolean
  address?: boolean
  sn?: boolean
  modem_type?: boolean
  status?: boolean
  last_uptime?: boolean
  rx_power_dbm?: boolean
  rx_power_str?: boolean
  raw_ifindex?: boolean
  raw_onuid?: boolean
  last_updated?: boolean
}, ExtArgs["result"]["snmp"]>

export type snmpSelectScalar = {
  olt_name?: boolean
  interface?: boolean
  name?: boolean
  address?: boolean
  sn?: boolean
  modem_type?: boolean
  status?: boolean
  last_uptime?: boolean
  rx_power_dbm?: boolean
  rx_power_str?: boolean
  raw_ifindex?: boolean
  raw_onuid?: boolean
  last_updated?: boolean
}

export type snmpOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"olt_name" | "interface" | "name" | "address" | "sn" | "modem_type" | "status" | "last_uptime" | "rx_power_dbm" | "rx_power_str" | "raw_ifindex" | "raw_onuid" | "last_updated", ExtArgs["result"]["snmp"]>

export type $snmpPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "snmp"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    olt_name: string
    interface: string
    name: string | null
    address: string | null
    sn: string | null
    modem_type: string | null
    status: string | null
    last_uptime: string | null
    rx_power_dbm: number | null
    rx_power_str: string | null
    raw_ifindex: string | null
    raw_onuid: string | null
    last_updated: Date | null
  }, ExtArgs["result"]["snmp"]>
  composites: {}
}

export type snmpGetPayload<S extends boolean | null | undefined | snmpDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$snmpPayload, S>

export type snmpCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<snmpFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SnmpCountAggregateInputType | true
  }

export interface snmpDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['snmp'], meta: { name: 'snmp' } }
  /**
   * Find zero or one Snmp that matches the filter.
   * @param {snmpFindUniqueArgs} args - Arguments to find a Snmp
   * @example
   * // Get one Snmp
   * const snmp = await prisma.snmp.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends snmpFindUniqueArgs>(args: Prisma.SelectSubset<T, snmpFindUniqueArgs<ExtArgs>>): Prisma.Prisma__snmpClient<runtime.Types.Result.GetResult<Prisma.$snmpPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Snmp that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {snmpFindUniqueOrThrowArgs} args - Arguments to find a Snmp
   * @example
   * // Get one Snmp
   * const snmp = await prisma.snmp.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends snmpFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, snmpFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__snmpClient<runtime.Types.Result.GetResult<Prisma.$snmpPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Snmp that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {snmpFindFirstArgs} args - Arguments to find a Snmp
   * @example
   * // Get one Snmp
   * const snmp = await prisma.snmp.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends snmpFindFirstArgs>(args?: Prisma.SelectSubset<T, snmpFindFirstArgs<ExtArgs>>): Prisma.Prisma__snmpClient<runtime.Types.Result.GetResult<Prisma.$snmpPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Snmp that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {snmpFindFirstOrThrowArgs} args - Arguments to find a Snmp
   * @example
   * // Get one Snmp
   * const snmp = await prisma.snmp.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends snmpFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, snmpFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__snmpClient<runtime.Types.Result.GetResult<Prisma.$snmpPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Snmps that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {snmpFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Snmps
   * const snmps = await prisma.snmp.findMany()
   * 
   * // Get first 10 Snmps
   * const snmps = await prisma.snmp.findMany({ take: 10 })
   * 
   * // Only select the `olt_name`
   * const snmpWithOlt_nameOnly = await prisma.snmp.findMany({ select: { olt_name: true } })
   * 
   */
  findMany<T extends snmpFindManyArgs>(args?: Prisma.SelectSubset<T, snmpFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$snmpPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Snmp.
   * @param {snmpCreateArgs} args - Arguments to create a Snmp.
   * @example
   * // Create one Snmp
   * const Snmp = await prisma.snmp.create({
   *   data: {
   *     // ... data to create a Snmp
   *   }
   * })
   * 
   */
  create<T extends snmpCreateArgs>(args: Prisma.SelectSubset<T, snmpCreateArgs<ExtArgs>>): Prisma.Prisma__snmpClient<runtime.Types.Result.GetResult<Prisma.$snmpPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Snmps.
   * @param {snmpCreateManyArgs} args - Arguments to create many Snmps.
   * @example
   * // Create many Snmps
   * const snmp = await prisma.snmp.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends snmpCreateManyArgs>(args?: Prisma.SelectSubset<T, snmpCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Snmps and returns the data saved in the database.
   * @param {snmpCreateManyAndReturnArgs} args - Arguments to create many Snmps.
   * @example
   * // Create many Snmps
   * const snmp = await prisma.snmp.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Snmps and only return the `olt_name`
   * const snmpWithOlt_nameOnly = await prisma.snmp.createManyAndReturn({
   *   select: { olt_name: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends snmpCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, snmpCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$snmpPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Snmp.
   * @param {snmpDeleteArgs} args - Arguments to delete one Snmp.
   * @example
   * // Delete one Snmp
   * const Snmp = await prisma.snmp.delete({
   *   where: {
   *     // ... filter to delete one Snmp
   *   }
   * })
   * 
   */
  delete<T extends snmpDeleteArgs>(args: Prisma.SelectSubset<T, snmpDeleteArgs<ExtArgs>>): Prisma.Prisma__snmpClient<runtime.Types.Result.GetResult<Prisma.$snmpPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Snmp.
   * @param {snmpUpdateArgs} args - Arguments to update one Snmp.
   * @example
   * // Update one Snmp
   * const snmp = await prisma.snmp.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends snmpUpdateArgs>(args: Prisma.SelectSubset<T, snmpUpdateArgs<ExtArgs>>): Prisma.Prisma__snmpClient<runtime.Types.Result.GetResult<Prisma.$snmpPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Snmps.
   * @param {snmpDeleteManyArgs} args - Arguments to filter Snmps to delete.
   * @example
   * // Delete a few Snmps
   * const { count } = await prisma.snmp.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends snmpDeleteManyArgs>(args?: Prisma.SelectSubset<T, snmpDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Snmps.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {snmpUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Snmps
   * const snmp = await prisma.snmp.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends snmpUpdateManyArgs>(args: Prisma.SelectSubset<T, snmpUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Snmps and returns the data updated in the database.
   * @param {snmpUpdateManyAndReturnArgs} args - Arguments to update many Snmps.
   * @example
   * // Update many Snmps
   * const snmp = await prisma.snmp.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Snmps and only return the `olt_name`
   * const snmpWithOlt_nameOnly = await prisma.snmp.updateManyAndReturn({
   *   select: { olt_name: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends snmpUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, snmpUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$snmpPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Snmp.
   * @param {snmpUpsertArgs} args - Arguments to update or create a Snmp.
   * @example
   * // Update or create a Snmp
   * const snmp = await prisma.snmp.upsert({
   *   create: {
   *     // ... data to create a Snmp
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Snmp we want to update
   *   }
   * })
   */
  upsert<T extends snmpUpsertArgs>(args: Prisma.SelectSubset<T, snmpUpsertArgs<ExtArgs>>): Prisma.Prisma__snmpClient<runtime.Types.Result.GetResult<Prisma.$snmpPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Snmps.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {snmpCountArgs} args - Arguments to filter Snmps to count.
   * @example
   * // Count the number of Snmps
   * const count = await prisma.snmp.count({
   *   where: {
   *     // ... the filter for the Snmps we want to count
   *   }
   * })
  **/
  count<T extends snmpCountArgs>(
    args?: Prisma.Subset<T, snmpCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SnmpCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Snmp.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SnmpAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SnmpAggregateArgs>(args: Prisma.Subset<T, SnmpAggregateArgs>): Prisma.PrismaPromise<GetSnmpAggregateType<T>>

  /**
   * Group by Snmp.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {snmpGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends snmpGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: snmpGroupByArgs['orderBy'] }
      : { orderBy?: snmpGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, snmpGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSnmpGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the snmp model
 */
readonly fields: snmpFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for snmp.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__snmpClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the snmp model
 */
export interface snmpFieldRefs {
  readonly olt_name: Prisma.FieldRef<"snmp", 'String'>
  readonly interface: Prisma.FieldRef<"snmp", 'String'>
  readonly name: Prisma.FieldRef<"snmp", 'String'>
  readonly address: Prisma.FieldRef<"snmp", 'String'>
  readonly sn: Prisma.FieldRef<"snmp", 'String'>
  readonly modem_type: Prisma.FieldRef<"snmp", 'String'>
  readonly status: Prisma.FieldRef<"snmp", 'String'>
  readonly last_uptime: Prisma.FieldRef<"snmp", 'String'>
  readonly rx_power_dbm: Prisma.FieldRef<"snmp", 'Float'>
  readonly rx_power_str: Prisma.FieldRef<"snmp", 'String'>
  readonly raw_ifindex: Prisma.FieldRef<"snmp", 'String'>
  readonly raw_onuid: Prisma.FieldRef<"snmp", 'String'>
  readonly last_updated: Prisma.FieldRef<"snmp", 'DateTime'>
}
    

// Custom InputTypes
/**
 * snmp findUnique
 */
export type snmpFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the snmp
   */
  select?: Prisma.snmpSelect<ExtArgs> | null
  /**
   * Omit specific fields from the snmp
   */
  omit?: Prisma.snmpOmit<ExtArgs> | null
  /**
   * Filter, which snmp to fetch.
   */
  where: Prisma.snmpWhereUniqueInput
}

/**
 * snmp findUniqueOrThrow
 */
export type snmpFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the snmp
   */
  select?: Prisma.snmpSelect<ExtArgs> | null
  /**
   * Omit specific fields from the snmp
   */
  omit?: Prisma.snmpOmit<ExtArgs> | null
  /**
   * Filter, which snmp to fetch.
   */
  where: Prisma.snmpWhereUniqueInput
}

/**
 * snmp findFirst
 */
export type snmpFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the snmp
   */
  select?: Prisma.snmpSelect<ExtArgs> | null
  /**
   * Omit specific fields from the snmp
   */
  omit?: Prisma.snmpOmit<ExtArgs> | null
  /**
   * Filter, which snmp to fetch.
   */
  where?: Prisma.snmpWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of snmps to fetch.
   */
  orderBy?: Prisma.snmpOrderByWithRelationInput | Prisma.snmpOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for snmps.
   */
  cursor?: Prisma.snmpWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` snmps from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` snmps.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of snmps.
   */
  distinct?: Prisma.SnmpScalarFieldEnum | Prisma.SnmpScalarFieldEnum[]
}

/**
 * snmp findFirstOrThrow
 */
export type snmpFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the snmp
   */
  select?: Prisma.snmpSelect<ExtArgs> | null
  /**
   * Omit specific fields from the snmp
   */
  omit?: Prisma.snmpOmit<ExtArgs> | null
  /**
   * Filter, which snmp to fetch.
   */
  where?: Prisma.snmpWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of snmps to fetch.
   */
  orderBy?: Prisma.snmpOrderByWithRelationInput | Prisma.snmpOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for snmps.
   */
  cursor?: Prisma.snmpWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` snmps from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` snmps.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of snmps.
   */
  distinct?: Prisma.SnmpScalarFieldEnum | Prisma.SnmpScalarFieldEnum[]
}

/**
 * snmp findMany
 */
export type snmpFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the snmp
   */
  select?: Prisma.snmpSelect<ExtArgs> | null
  /**
   * Omit specific fields from the snmp
   */
  omit?: Prisma.snmpOmit<ExtArgs> | null
  /**
   * Filter, which snmps to fetch.
   */
  where?: Prisma.snmpWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of snmps to fetch.
   */
  orderBy?: Prisma.snmpOrderByWithRelationInput | Prisma.snmpOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing snmps.
   */
  cursor?: Prisma.snmpWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` snmps from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` snmps.
   */
  skip?: number
  distinct?: Prisma.SnmpScalarFieldEnum | Prisma.SnmpScalarFieldEnum[]
}

/**
 * snmp create
 */
export type snmpCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the snmp
   */
  select?: Prisma.snmpSelect<ExtArgs> | null
  /**
   * Omit specific fields from the snmp
   */
  omit?: Prisma.snmpOmit<ExtArgs> | null
  /**
   * The data needed to create a snmp.
   */
  data: Prisma.XOR<Prisma.snmpCreateInput, Prisma.snmpUncheckedCreateInput>
}

/**
 * snmp createMany
 */
export type snmpCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many snmps.
   */
  data: Prisma.snmpCreateManyInput | Prisma.snmpCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * snmp createManyAndReturn
 */
export type snmpCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the snmp
   */
  select?: Prisma.snmpSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the snmp
   */
  omit?: Prisma.snmpOmit<ExtArgs> | null
  /**
   * The data used to create many snmps.
   */
  data: Prisma.snmpCreateManyInput | Prisma.snmpCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * snmp update
 */
export type snmpUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the snmp
   */
  select?: Prisma.snmpSelect<ExtArgs> | null
  /**
   * Omit specific fields from the snmp
   */
  omit?: Prisma.snmpOmit<ExtArgs> | null
  /**
   * The data needed to update a snmp.
   */
  data: Prisma.XOR<Prisma.snmpUpdateInput, Prisma.snmpUncheckedUpdateInput>
  /**
   * Choose, which snmp to update.
   */
  where: Prisma.snmpWhereUniqueInput
}

/**
 * snmp updateMany
 */
export type snmpUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update snmps.
   */
  data: Prisma.XOR<Prisma.snmpUpdateManyMutationInput, Prisma.snmpUncheckedUpdateManyInput>
  /**
   * Filter which snmps to update
   */
  where?: Prisma.snmpWhereInput
  /**
   * Limit how many snmps to update.
   */
  limit?: number
}

/**
 * snmp updateManyAndReturn
 */
export type snmpUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the snmp
   */
  select?: Prisma.snmpSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the snmp
   */
  omit?: Prisma.snmpOmit<ExtArgs> | null
  /**
   * The data used to update snmps.
   */
  data: Prisma.XOR<Prisma.snmpUpdateManyMutationInput, Prisma.snmpUncheckedUpdateManyInput>
  /**
   * Filter which snmps to update
   */
  where?: Prisma.snmpWhereInput
  /**
   * Limit how many snmps to update.
   */
  limit?: number
}

/**
 * snmp upsert
 */
export type snmpUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the snmp
   */
  select?: Prisma.snmpSelect<ExtArgs> | null
  /**
   * Omit specific fields from the snmp
   */
  omit?: Prisma.snmpOmit<ExtArgs> | null
  /**
   * The filter to search for the snmp to update in case it exists.
   */
  where: Prisma.snmpWhereUniqueInput
  /**
   * In case the snmp found by the `where` argument doesn't exist, create a new snmp with this data.
   */
  create: Prisma.XOR<Prisma.snmpCreateInput, Prisma.snmpUncheckedCreateInput>
  /**
   * In case the snmp was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.snmpUpdateInput, Prisma.snmpUncheckedUpdateInput>
}

/**
 * snmp delete
 */
export type snmpDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the snmp
   */
  select?: Prisma.snmpSelect<ExtArgs> | null
  /**
   * Omit specific fields from the snmp
   */
  omit?: Prisma.snmpOmit<ExtArgs> | null
  /**
   * Filter which snmp to delete.
   */
  where: Prisma.snmpWhereUniqueInput
}

/**
 * snmp deleteMany
 */
export type snmpDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which snmps to delete
   */
  where?: Prisma.snmpWhereInput
  /**
   * Limit how many snmps to delete.
   */
  limit?: number
}

/**
 * snmp without action
 */
export type snmpDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the snmp
   */
  select?: Prisma.snmpSelect<ExtArgs> | null
  /**
   * Omit specific fields from the snmp
   */
  omit?: Prisma.snmpOmit<ExtArgs> | null
}
