
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `snmp_devices` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model snmp_devices
 * 
 */
export type snmp_devicesModel = runtime.Types.Result.DefaultSelection<Prisma.$snmp_devicesPayload>

export type AggregateSnmp_devices = {
  _count: Snmp_devicesCountAggregateOutputType | null
  _min: Snmp_devicesMinAggregateOutputType | null
  _max: Snmp_devicesMaxAggregateOutputType | null
}

export type Snmp_devicesMinAggregateOutputType = {
  name: string | null
  host: string | null
  community_string: string | null
}

export type Snmp_devicesMaxAggregateOutputType = {
  name: string | null
  host: string | null
  community_string: string | null
}

export type Snmp_devicesCountAggregateOutputType = {
  name: number
  host: number
  community_string: number
  _all: number
}


export type Snmp_devicesMinAggregateInputType = {
  name?: true
  host?: true
  community_string?: true
}

export type Snmp_devicesMaxAggregateInputType = {
  name?: true
  host?: true
  community_string?: true
}

export type Snmp_devicesCountAggregateInputType = {
  name?: true
  host?: true
  community_string?: true
  _all?: true
}

export type Snmp_devicesAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which snmp_devices to aggregate.
   */
  where?: Prisma.snmp_devicesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of snmp_devices to fetch.
   */
  orderBy?: Prisma.snmp_devicesOrderByWithRelationInput | Prisma.snmp_devicesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.snmp_devicesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` snmp_devices from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` snmp_devices.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned snmp_devices
  **/
  _count?: true | Snmp_devicesCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Snmp_devicesMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Snmp_devicesMaxAggregateInputType
}

export type GetSnmp_devicesAggregateType<T extends Snmp_devicesAggregateArgs> = {
      [P in keyof T & keyof AggregateSnmp_devices]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSnmp_devices[P]>
    : Prisma.GetScalarType<T[P], AggregateSnmp_devices[P]>
}




export type snmp_devicesGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.snmp_devicesWhereInput
  orderBy?: Prisma.snmp_devicesOrderByWithAggregationInput | Prisma.snmp_devicesOrderByWithAggregationInput[]
  by: Prisma.Snmp_devicesScalarFieldEnum[] | Prisma.Snmp_devicesScalarFieldEnum
  having?: Prisma.snmp_devicesScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Snmp_devicesCountAggregateInputType | true
  _min?: Snmp_devicesMinAggregateInputType
  _max?: Snmp_devicesMaxAggregateInputType
}

export type Snmp_devicesGroupByOutputType = {
  name: string
  host: string
  community_string: string
  _count: Snmp_devicesCountAggregateOutputType | null
  _min: Snmp_devicesMinAggregateOutputType | null
  _max: Snmp_devicesMaxAggregateOutputType | null
}

type GetSnmp_devicesGroupByPayload<T extends snmp_devicesGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Snmp_devicesGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Snmp_devicesGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Snmp_devicesGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Snmp_devicesGroupByOutputType[P]>
      }
    >
  >



export type snmp_devicesWhereInput = {
  AND?: Prisma.snmp_devicesWhereInput | Prisma.snmp_devicesWhereInput[]
  OR?: Prisma.snmp_devicesWhereInput[]
  NOT?: Prisma.snmp_devicesWhereInput | Prisma.snmp_devicesWhereInput[]
  name?: Prisma.StringFilter<"snmp_devices"> | string
  host?: Prisma.StringFilter<"snmp_devices"> | string
  community_string?: Prisma.StringFilter<"snmp_devices"> | string
}

export type snmp_devicesOrderByWithRelationInput = {
  name?: Prisma.SortOrder
  host?: Prisma.SortOrder
  community_string?: Prisma.SortOrder
}

export type snmp_devicesWhereUniqueInput = Prisma.AtLeast<{
  name?: string
  AND?: Prisma.snmp_devicesWhereInput | Prisma.snmp_devicesWhereInput[]
  OR?: Prisma.snmp_devicesWhereInput[]
  NOT?: Prisma.snmp_devicesWhereInput | Prisma.snmp_devicesWhereInput[]
  host?: Prisma.StringFilter<"snmp_devices"> | string
  community_string?: Prisma.StringFilter<"snmp_devices"> | string
}, "name">

export type snmp_devicesOrderByWithAggregationInput = {
  name?: Prisma.SortOrder
  host?: Prisma.SortOrder
  community_string?: Prisma.SortOrder
  _count?: Prisma.snmp_devicesCountOrderByAggregateInput
  _max?: Prisma.snmp_devicesMaxOrderByAggregateInput
  _min?: Prisma.snmp_devicesMinOrderByAggregateInput
}

export type snmp_devicesScalarWhereWithAggregatesInput = {
  AND?: Prisma.snmp_devicesScalarWhereWithAggregatesInput | Prisma.snmp_devicesScalarWhereWithAggregatesInput[]
  OR?: Prisma.snmp_devicesScalarWhereWithAggregatesInput[]
  NOT?: Prisma.snmp_devicesScalarWhereWithAggregatesInput | Prisma.snmp_devicesScalarWhereWithAggregatesInput[]
  name?: Prisma.StringWithAggregatesFilter<"snmp_devices"> | string
  host?: Prisma.StringWithAggregatesFilter<"snmp_devices"> | string
  community_string?: Prisma.StringWithAggregatesFilter<"snmp_devices"> | string
}

export type snmp_devicesCreateInput = {
  name: string
  host: string
  community_string?: string
}

export type snmp_devicesUncheckedCreateInput = {
  name: string
  host: string
  community_string?: string
}

export type snmp_devicesUpdateInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  host?: Prisma.StringFieldUpdateOperationsInput | string
  community_string?: Prisma.StringFieldUpdateOperationsInput | string
}

export type snmp_devicesUncheckedUpdateInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  host?: Prisma.StringFieldUpdateOperationsInput | string
  community_string?: Prisma.StringFieldUpdateOperationsInput | string
}

export type snmp_devicesCreateManyInput = {
  name: string
  host: string
  community_string?: string
}

export type snmp_devicesUpdateManyMutationInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  host?: Prisma.StringFieldUpdateOperationsInput | string
  community_string?: Prisma.StringFieldUpdateOperationsInput | string
}

export type snmp_devicesUncheckedUpdateManyInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  host?: Prisma.StringFieldUpdateOperationsInput | string
  community_string?: Prisma.StringFieldUpdateOperationsInput | string
}

export type snmp_devicesCountOrderByAggregateInput = {
  name?: Prisma.SortOrder
  host?: Prisma.SortOrder
  community_string?: Prisma.SortOrder
}

export type snmp_devicesMaxOrderByAggregateInput = {
  name?: Prisma.SortOrder
  host?: Prisma.SortOrder
  community_string?: Prisma.SortOrder
}

export type snmp_devicesMinOrderByAggregateInput = {
  name?: Prisma.SortOrder
  host?: Prisma.SortOrder
  community_string?: Prisma.SortOrder
}



export type snmp_devicesSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  name?: boolean
  host?: boolean
  community_string?: boolean
}, ExtArgs["result"]["snmp_devices"]>

export type snmp_devicesSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  name?: boolean
  host?: boolean
  community_string?: boolean
}, ExtArgs["result"]["snmp_devices"]>

export type snmp_devicesSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  name?: boolean
  host?: boolean
  community_string?: boolean
}, ExtArgs["result"]["snmp_devices"]>

export type snmp_devicesSelectScalar = {
  name?: boolean
  host?: boolean
  community_string?: boolean
}

export type snmp_devicesOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"name" | "host" | "community_string", ExtArgs["result"]["snmp_devices"]>

export type $snmp_devicesPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "snmp_devices"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    name: string
    host: string
    community_string: string
  }, ExtArgs["result"]["snmp_devices"]>
  composites: {}
}

export type snmp_devicesGetPayload<S extends boolean | null | undefined | snmp_devicesDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$snmp_devicesPayload, S>

export type snmp_devicesCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<snmp_devicesFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Snmp_devicesCountAggregateInputType | true
  }

export interface snmp_devicesDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['snmp_devices'], meta: { name: 'snmp_devices' } }
  /**
   * Find zero or one Snmp_devices that matches the filter.
   * @param {snmp_devicesFindUniqueArgs} args - Arguments to find a Snmp_devices
   * @example
   * // Get one Snmp_devices
   * const snmp_devices = await prisma.snmp_devices.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends snmp_devicesFindUniqueArgs>(args: Prisma.SelectSubset<T, snmp_devicesFindUniqueArgs<ExtArgs>>): Prisma.Prisma__snmp_devicesClient<runtime.Types.Result.GetResult<Prisma.$snmp_devicesPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Snmp_devices that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {snmp_devicesFindUniqueOrThrowArgs} args - Arguments to find a Snmp_devices
   * @example
   * // Get one Snmp_devices
   * const snmp_devices = await prisma.snmp_devices.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends snmp_devicesFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, snmp_devicesFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__snmp_devicesClient<runtime.Types.Result.GetResult<Prisma.$snmp_devicesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Snmp_devices that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {snmp_devicesFindFirstArgs} args - Arguments to find a Snmp_devices
   * @example
   * // Get one Snmp_devices
   * const snmp_devices = await prisma.snmp_devices.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends snmp_devicesFindFirstArgs>(args?: Prisma.SelectSubset<T, snmp_devicesFindFirstArgs<ExtArgs>>): Prisma.Prisma__snmp_devicesClient<runtime.Types.Result.GetResult<Prisma.$snmp_devicesPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Snmp_devices that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {snmp_devicesFindFirstOrThrowArgs} args - Arguments to find a Snmp_devices
   * @example
   * // Get one Snmp_devices
   * const snmp_devices = await prisma.snmp_devices.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends snmp_devicesFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, snmp_devicesFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__snmp_devicesClient<runtime.Types.Result.GetResult<Prisma.$snmp_devicesPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Snmp_devices that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {snmp_devicesFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Snmp_devices
   * const snmp_devices = await prisma.snmp_devices.findMany()
   * 
   * // Get first 10 Snmp_devices
   * const snmp_devices = await prisma.snmp_devices.findMany({ take: 10 })
   * 
   * // Only select the `name`
   * const snmp_devicesWithNameOnly = await prisma.snmp_devices.findMany({ select: { name: true } })
   * 
   */
  findMany<T extends snmp_devicesFindManyArgs>(args?: Prisma.SelectSubset<T, snmp_devicesFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$snmp_devicesPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Snmp_devices.
   * @param {snmp_devicesCreateArgs} args - Arguments to create a Snmp_devices.
   * @example
   * // Create one Snmp_devices
   * const Snmp_devices = await prisma.snmp_devices.create({
   *   data: {
   *     // ... data to create a Snmp_devices
   *   }
   * })
   * 
   */
  create<T extends snmp_devicesCreateArgs>(args: Prisma.SelectSubset<T, snmp_devicesCreateArgs<ExtArgs>>): Prisma.Prisma__snmp_devicesClient<runtime.Types.Result.GetResult<Prisma.$snmp_devicesPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Snmp_devices.
   * @param {snmp_devicesCreateManyArgs} args - Arguments to create many Snmp_devices.
   * @example
   * // Create many Snmp_devices
   * const snmp_devices = await prisma.snmp_devices.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends snmp_devicesCreateManyArgs>(args?: Prisma.SelectSubset<T, snmp_devicesCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Snmp_devices and returns the data saved in the database.
   * @param {snmp_devicesCreateManyAndReturnArgs} args - Arguments to create many Snmp_devices.
   * @example
   * // Create many Snmp_devices
   * const snmp_devices = await prisma.snmp_devices.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Snmp_devices and only return the `name`
   * const snmp_devicesWithNameOnly = await prisma.snmp_devices.createManyAndReturn({
   *   select: { name: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends snmp_devicesCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, snmp_devicesCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$snmp_devicesPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Snmp_devices.
   * @param {snmp_devicesDeleteArgs} args - Arguments to delete one Snmp_devices.
   * @example
   * // Delete one Snmp_devices
   * const Snmp_devices = await prisma.snmp_devices.delete({
   *   where: {
   *     // ... filter to delete one Snmp_devices
   *   }
   * })
   * 
   */
  delete<T extends snmp_devicesDeleteArgs>(args: Prisma.SelectSubset<T, snmp_devicesDeleteArgs<ExtArgs>>): Prisma.Prisma__snmp_devicesClient<runtime.Types.Result.GetResult<Prisma.$snmp_devicesPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Snmp_devices.
   * @param {snmp_devicesUpdateArgs} args - Arguments to update one Snmp_devices.
   * @example
   * // Update one Snmp_devices
   * const snmp_devices = await prisma.snmp_devices.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends snmp_devicesUpdateArgs>(args: Prisma.SelectSubset<T, snmp_devicesUpdateArgs<ExtArgs>>): Prisma.Prisma__snmp_devicesClient<runtime.Types.Result.GetResult<Prisma.$snmp_devicesPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Snmp_devices.
   * @param {snmp_devicesDeleteManyArgs} args - Arguments to filter Snmp_devices to delete.
   * @example
   * // Delete a few Snmp_devices
   * const { count } = await prisma.snmp_devices.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends snmp_devicesDeleteManyArgs>(args?: Prisma.SelectSubset<T, snmp_devicesDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Snmp_devices.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {snmp_devicesUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Snmp_devices
   * const snmp_devices = await prisma.snmp_devices.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends snmp_devicesUpdateManyArgs>(args: Prisma.SelectSubset<T, snmp_devicesUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Snmp_devices and returns the data updated in the database.
   * @param {snmp_devicesUpdateManyAndReturnArgs} args - Arguments to update many Snmp_devices.
   * @example
   * // Update many Snmp_devices
   * const snmp_devices = await prisma.snmp_devices.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Snmp_devices and only return the `name`
   * const snmp_devicesWithNameOnly = await prisma.snmp_devices.updateManyAndReturn({
   *   select: { name: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends snmp_devicesUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, snmp_devicesUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$snmp_devicesPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Snmp_devices.
   * @param {snmp_devicesUpsertArgs} args - Arguments to update or create a Snmp_devices.
   * @example
   * // Update or create a Snmp_devices
   * const snmp_devices = await prisma.snmp_devices.upsert({
   *   create: {
   *     // ... data to create a Snmp_devices
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Snmp_devices we want to update
   *   }
   * })
   */
  upsert<T extends snmp_devicesUpsertArgs>(args: Prisma.SelectSubset<T, snmp_devicesUpsertArgs<ExtArgs>>): Prisma.Prisma__snmp_devicesClient<runtime.Types.Result.GetResult<Prisma.$snmp_devicesPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Snmp_devices.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {snmp_devicesCountArgs} args - Arguments to filter Snmp_devices to count.
   * @example
   * // Count the number of Snmp_devices
   * const count = await prisma.snmp_devices.count({
   *   where: {
   *     // ... the filter for the Snmp_devices we want to count
   *   }
   * })
  **/
  count<T extends snmp_devicesCountArgs>(
    args?: Prisma.Subset<T, snmp_devicesCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Snmp_devicesCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Snmp_devices.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Snmp_devicesAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Snmp_devicesAggregateArgs>(args: Prisma.Subset<T, Snmp_devicesAggregateArgs>): Prisma.PrismaPromise<GetSnmp_devicesAggregateType<T>>

  /**
   * Group by Snmp_devices.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {snmp_devicesGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends snmp_devicesGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: snmp_devicesGroupByArgs['orderBy'] }
      : { orderBy?: snmp_devicesGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, snmp_devicesGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSnmp_devicesGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the snmp_devices model
 */
readonly fields: snmp_devicesFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for snmp_devices.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__snmp_devicesClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the snmp_devices model
 */
export interface snmp_devicesFieldRefs {
  readonly name: Prisma.FieldRef<"snmp_devices", 'String'>
  readonly host: Prisma.FieldRef<"snmp_devices", 'String'>
  readonly community_string: Prisma.FieldRef<"snmp_devices", 'String'>
}
    

// Custom InputTypes
/**
 * snmp_devices findUnique
 */
export type snmp_devicesFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the snmp_devices
   */
  select?: Prisma.snmp_devicesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the snmp_devices
   */
  omit?: Prisma.snmp_devicesOmit<ExtArgs> | null
  /**
   * Filter, which snmp_devices to fetch.
   */
  where: Prisma.snmp_devicesWhereUniqueInput
}

/**
 * snmp_devices findUniqueOrThrow
 */
export type snmp_devicesFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the snmp_devices
   */
  select?: Prisma.snmp_devicesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the snmp_devices
   */
  omit?: Prisma.snmp_devicesOmit<ExtArgs> | null
  /**
   * Filter, which snmp_devices to fetch.
   */
  where: Prisma.snmp_devicesWhereUniqueInput
}

/**
 * snmp_devices findFirst
 */
export type snmp_devicesFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the snmp_devices
   */
  select?: Prisma.snmp_devicesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the snmp_devices
   */
  omit?: Prisma.snmp_devicesOmit<ExtArgs> | null
  /**
   * Filter, which snmp_devices to fetch.
   */
  where?: Prisma.snmp_devicesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of snmp_devices to fetch.
   */
  orderBy?: Prisma.snmp_devicesOrderByWithRelationInput | Prisma.snmp_devicesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for snmp_devices.
   */
  cursor?: Prisma.snmp_devicesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` snmp_devices from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` snmp_devices.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of snmp_devices.
   */
  distinct?: Prisma.Snmp_devicesScalarFieldEnum | Prisma.Snmp_devicesScalarFieldEnum[]
}

/**
 * snmp_devices findFirstOrThrow
 */
export type snmp_devicesFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the snmp_devices
   */
  select?: Prisma.snmp_devicesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the snmp_devices
   */
  omit?: Prisma.snmp_devicesOmit<ExtArgs> | null
  /**
   * Filter, which snmp_devices to fetch.
   */
  where?: Prisma.snmp_devicesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of snmp_devices to fetch.
   */
  orderBy?: Prisma.snmp_devicesOrderByWithRelationInput | Prisma.snmp_devicesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for snmp_devices.
   */
  cursor?: Prisma.snmp_devicesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` snmp_devices from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` snmp_devices.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of snmp_devices.
   */
  distinct?: Prisma.Snmp_devicesScalarFieldEnum | Prisma.Snmp_devicesScalarFieldEnum[]
}

/**
 * snmp_devices findMany
 */
export type snmp_devicesFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the snmp_devices
   */
  select?: Prisma.snmp_devicesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the snmp_devices
   */
  omit?: Prisma.snmp_devicesOmit<ExtArgs> | null
  /**
   * Filter, which snmp_devices to fetch.
   */
  where?: Prisma.snmp_devicesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of snmp_devices to fetch.
   */
  orderBy?: Prisma.snmp_devicesOrderByWithRelationInput | Prisma.snmp_devicesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing snmp_devices.
   */
  cursor?: Prisma.snmp_devicesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` snmp_devices from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` snmp_devices.
   */
  skip?: number
  distinct?: Prisma.Snmp_devicesScalarFieldEnum | Prisma.Snmp_devicesScalarFieldEnum[]
}

/**
 * snmp_devices create
 */
export type snmp_devicesCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the snmp_devices
   */
  select?: Prisma.snmp_devicesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the snmp_devices
   */
  omit?: Prisma.snmp_devicesOmit<ExtArgs> | null
  /**
   * The data needed to create a snmp_devices.
   */
  data: Prisma.XOR<Prisma.snmp_devicesCreateInput, Prisma.snmp_devicesUncheckedCreateInput>
}

/**
 * snmp_devices createMany
 */
export type snmp_devicesCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many snmp_devices.
   */
  data: Prisma.snmp_devicesCreateManyInput | Prisma.snmp_devicesCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * snmp_devices createManyAndReturn
 */
export type snmp_devicesCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the snmp_devices
   */
  select?: Prisma.snmp_devicesSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the snmp_devices
   */
  omit?: Prisma.snmp_devicesOmit<ExtArgs> | null
  /**
   * The data used to create many snmp_devices.
   */
  data: Prisma.snmp_devicesCreateManyInput | Prisma.snmp_devicesCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * snmp_devices update
 */
export type snmp_devicesUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the snmp_devices
   */
  select?: Prisma.snmp_devicesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the snmp_devices
   */
  omit?: Prisma.snmp_devicesOmit<ExtArgs> | null
  /**
   * The data needed to update a snmp_devices.
   */
  data: Prisma.XOR<Prisma.snmp_devicesUpdateInput, Prisma.snmp_devicesUncheckedUpdateInput>
  /**
   * Choose, which snmp_devices to update.
   */
  where: Prisma.snmp_devicesWhereUniqueInput
}

/**
 * snmp_devices updateMany
 */
export type snmp_devicesUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update snmp_devices.
   */
  data: Prisma.XOR<Prisma.snmp_devicesUpdateManyMutationInput, Prisma.snmp_devicesUncheckedUpdateManyInput>
  /**
   * Filter which snmp_devices to update
   */
  where?: Prisma.snmp_devicesWhereInput
  /**
   * Limit how many snmp_devices to update.
   */
  limit?: number
}

/**
 * snmp_devices updateManyAndReturn
 */
export type snmp_devicesUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the snmp_devices
   */
  select?: Prisma.snmp_devicesSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the snmp_devices
   */
  omit?: Prisma.snmp_devicesOmit<ExtArgs> | null
  /**
   * The data used to update snmp_devices.
   */
  data: Prisma.XOR<Prisma.snmp_devicesUpdateManyMutationInput, Prisma.snmp_devicesUncheckedUpdateManyInput>
  /**
   * Filter which snmp_devices to update
   */
  where?: Prisma.snmp_devicesWhereInput
  /**
   * Limit how many snmp_devices to update.
   */
  limit?: number
}

/**
 * snmp_devices upsert
 */
export type snmp_devicesUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the snmp_devices
   */
  select?: Prisma.snmp_devicesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the snmp_devices
   */
  omit?: Prisma.snmp_devicesOmit<ExtArgs> | null
  /**
   * The filter to search for the snmp_devices to update in case it exists.
   */
  where: Prisma.snmp_devicesWhereUniqueInput
  /**
   * In case the snmp_devices found by the `where` argument doesn't exist, create a new snmp_devices with this data.
   */
  create: Prisma.XOR<Prisma.snmp_devicesCreateInput, Prisma.snmp_devicesUncheckedCreateInput>
  /**
   * In case the snmp_devices was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.snmp_devicesUpdateInput, Prisma.snmp_devicesUncheckedUpdateInput>
}

/**
 * snmp_devices delete
 */
export type snmp_devicesDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the snmp_devices
   */
  select?: Prisma.snmp_devicesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the snmp_devices
   */
  omit?: Prisma.snmp_devicesOmit<ExtArgs> | null
  /**
   * Filter which snmp_devices to delete.
   */
  where: Prisma.snmp_devicesWhereUniqueInput
}

/**
 * snmp_devices deleteMany
 */
export type snmp_devicesDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which snmp_devices to delete
   */
  where?: Prisma.snmp_devicesWhereInput
  /**
   * Limit how many snmp_devices to delete.
   */
  limit?: number
}

/**
 * snmp_devices without action
 */
export type snmp_devicesDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the snmp_devices
   */
  select?: Prisma.snmp_devicesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the snmp_devices
   */
  omit?: Prisma.snmp_devicesOmit<ExtArgs> | null
}
